### ISSUE TITLE
Split Post inside the Title edit box does weird stuff

### ISSUE THREAD

**Issue by randrey** [OpenLiveWriter/OpenLiveWriter#142]
1. Put cursor inside the title box.
2. Go to Insert and click 'Split post'
![split title](https://cloud.githubusercontent.com/assets/798485/11802502/54e1fabc-a2a6-11e5-8b88-2fb7e2553a3f.png)

This will insert a bunch of divs on top (or in place of the title box):

```html
<div class="body">

<div id="4179a726-05b2-4931-a35f-5c3506a5fb9d" class="postBody" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; padding-bottom: 0px; padding-top: 0px; padding-left: 0px; margin: 4px 0px 0px; padding-right: 0px; border-top-width: 0px">

<!--more-->
</div></div>
```

![thething](https://cloud.githubusercontent.com/assets/798485/11802599/568c9894-a2a7-11e5-927f-373247f00f2a.png)

Removing the thing that appears on top of the title box throws COM Exception:
>
System.Runtime.InteropServices.COMException (0x800A025B): Exception from HRESULT: 0x800A025B
   at OpenLiveWriter.Mshtml.IMarkupPointerRaw.IsLeftOf(IMarkupPointerRaw pPointerThat, Boolean& pfResult)
   at OpenLiveWriter.Mshtml.MarkupPointer.IsLeftOf(MarkupPointer p)
   at OpenLiveWriter.Mshtml.MarkupRange.InRange(MarkupPointer p, Boolean allowEquals)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.EditableRegionElementBehavior.QueryElementSelected()
   at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior.UpdateSelectionState()
   at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior._editorContext_SelectionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OnSelectionChanged(EventArgs e, IHtmlEditorSelection newSelection, Boolean moveSelectionToFont)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.ClearSelection(IHtmlEditorSelection selection)
   at OpenLiveWriter.HtmlEditor.HtmlEditorSelection.ExecuteSelectionOperation(HtmlEditorSelectionOperation op)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.Clear()
   at OpenLiveWriter.PostEditor.ContentEditor.Clear()
   at OpenLiveWriter.PostEditor.TextEditingCommandDispatcher.ClearCommand.Execute()
   at OpenLiveWriter.PostEditor.TextEditingCommandDispatcher.TextEditingCommand.Execute(Object sender, EventArgs ea)
   at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.OnExecute(EventArgs e)

**Comment by willduff** [comment]
The split post actually goes into the body of the blog post though, but something weird is definitely going on.

**Comment by willduff** [comment]
Implementation for this is in the `OpenLiveWriter.PostEditor.PostHtmlEditing.Behaviors.ExtendedEntrySplitterElementBehavior` class. Check out other implementations of MshtmlElementBehavior to see what might be going wrong. For example, the image editing is implemented in the `OpenLiveWriter.PostEditor.PostHtmlEditing.ImageEditingElementBehavior` class.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
