### ISSUE TITLE
Pasting an image from clipboard doesn't work well.

### ISSUE THREAD

**Issue by randrey** [OpenLiveWriter/OpenLiveWriter#143]
I'm observing two behaviors - it either pastes image in a 1 pixel box or doesn't work at all.
Repro for the first case:
1. PrintScreen
2. CTRL+V
Result:
![copypastepixels](https://cloud.githubusercontent.com/assets/798485/11803463/0b94baa2-a2b0-11e5-9def-3e95267acf8a.png)
It is resizable, but still.. maybe make it at least 300x300?

Not sure what's reason for the second, but I suspect aspect ratio. Can't paste a ~1600x100 image. The log says

>
OpenLiveWriter,1.12500,None,00030,14-Dec-2015 22:19:27.726,"Could not initialize image: C:\Users\z\AppData\Local\Temp\OpenLiveWriter-1390048565\A35A7BDBF481\image.png",""
OpenLiveWriter,1.12500,None,00031,14-Dec-2015 22:19:27.726,"System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at OpenLiveWriter.CoreServices.ImageHelper2.ImageResizer.RGBResize(Bitmap bitmap, Int32 xSize, Int32 ySize)
   at OpenLiveWriter.CoreServices.ImageHelper2.ImageResizer.ResizeBitmap(Bitmap bitmap, Int32 xSize, Int32 ySize, ImageFormat format)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.ImageInitializationAsyncOperation.DoWork()",""

**Comment by ScottIsAFool** [comment]
Are you able to reproduce this consistently at all? I've not been able to at all.

**Comment by randrey** [comment]
Consistent on my machine :)

**Comment by ScottIsAFool** [comment]
What OS? Are you able to share the image at all so I can try it here?

**Comment by randrey** [comment]
Win 10. 
[imagesample.zip](https://github.com/OpenLiveWriter/OpenLiveWriter/files/64928/imagesample.zip)

**Comment by heyduke50** [comment]
I can paste images from the clipboard fine but when I go to post I get a 403 error returned

**Comment by willduff** [comment]
@randrey, are you able to debug through this with Visual Studio and tell me what `PixelFormat` is being passed? It seems you're missing an image encoder/decoder on your machine.

**Comment by dougrathbone** [comment]
Fix submitted in #1082 — ensures pasted images have at least 16x16 dimensions and re-reads actual size from the image file. Includes 8 unit tests.
