### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by banders03** [OpenLiveWriter/OpenLiveWriter#151]
I still can't log in. I know my username and password are correct--I verified it with Blogger and I keep getting told my username or password are incorrect. I miss LW so much and really want to use OLW--what can the problem be?

**Comment by ScottIsAFool** [comment]
Hi, we have just pushed an update to address this. Can you please launch the app, wait a minute or so, then close it. Then try launching it again. Now when you get to the choose blog type, you should be able to select Google Blogger.

**Comment by banders03** [comment]
Yes!! It's now setting up my blog account...and has opened up!! yay!! Thank you!!

**Comment by ScottIsAFool** [comment]
Enjoy

**Comment by banders03** [comment]
I did a test page and got this error message:

GoogleApiException
The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()
