### ISSUE TITLE
'rem' (CSS3's root em) detected as 'em' and CSS float number conversion fails

### ISSUE THREAD

**Issue by vhanla** [OpenLiveWriter/OpenLiveWriter#178]
**_Notice that this error only appears running the debug binary.**_

Error message:

``` csharp
Failed to convert CSS units: System.FormatException: Input string was not in a correct format.
  at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
  at System.Convert.ToDouble(String value, IFormatProvider provider)
```

File: OpenLiveWriter.CoreServices\HTML\HTMLElementHelper.cs

**My template uses CSS3** _rem_, and since this file's code has not _rem_ support, it fails, as the following lines (from that file's source code) will detect _'em'_ and it tries to convert from something like this (e.g.) **1.4rem** to float, consequently it will try to convert **1.4r** to float instead of **1.4** which is wrong, since it expects to be _em_ instead.

``` csharp
// RELATIVE SIZE
i = cssUnits.IndexOf("EM", StringComparison.OrdinalIgnoreCase);
if (i > 0)
{
  float parentMultiplier = (float)Convert.ToDouble(cssUnits.Substring(0, i), CultureInfo.InvariantCulture);
 ...
```

Anyway, since _rem_ is relative to root element (HTML) itself, then it should be added too:

Here is an attempt which I'm not really sure if that is how it should be handled _rem_ 

``` csharp
// CSS3 RELATIVE SIZE TO ROOT HTML
i = cssUnits.IndexOf("REM", StringComparison.OrdinalIgnoreCase);
if (i > 0)
{
   float rootMultiplier = (float)Convert.ToDouble(cssUnits.Substring(0, i), CultureInfo.InstalledUICulture);
   IHTMLElement rootElement = element;
   while (rootElement.parentElement != null) // until it encounters {mshtml.HTMLHtmlElementClass} which is the root HTML node
    {
        rootElement = rootElement.parentElement;
    }

    // the 'rem' unit is relative to the computed value of the font-size attribute of the root element.
    return rootMultiplier * CSSUnitStringToPointSize(CSSUnitStringFontSize, rootElement, LastChanceFontPointSize, vertical);
}
```

Of course that will prepend the previous code to avoid detecting _em_ first.

**Comment by dougrathbone** [comment]
The REM vs EM parsing issue was already fixed in commit e2666576 which added REM handling before EM detection. Closing as already resolved.
