### ISSUE TITLE
win10 installation error logs

### ISSUE THREAD

**Issue by avaikinius** [OpenLiveWriter/OpenLiveWriter#195]
greetings all,

... thought I'd died and gone to heaven when I saw the announcement for Open Live Writer. **writer swoon**

So, yeah, issues, but no worries, you tech girls and boys will get writer right, ay :)

**Issue:** ... .exe installer fails, generates errors. Will retry after a restart. This is a fresh upgrade to Windows 10 and may need an equally fresh (re)install or clean install, but unable to at the moment because the desktop owner is away, and I don't want to mistakenly lose any files.

I'm pasting the error log below and as a file. 

2015-12-21 03:07:00> Program: Starting Squirrel Updater: --install .
2015-12-21 03:07:02> Program: Starting install, writing to C:\Users\jason\AppData\Local\SquirrelTemp
2015-12-21 03:07:04> Program: About to install to: C:\Users\jason\AppData\Local\OpenLiveWriter
2015-12-21 03:07:13> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2015-12-21 03:07:14> CheckForUpdateImpl: Reading RELEASES file from C:\Users\jason\AppData\Local\SquirrelTemp
2015-12-21 03:07:16> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-12-21 03:07:17> ApplyReleasesImpl: Writing files to app directory: C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\DeltaCompressionDotNet.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\DeltaCompressionDotNet.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\DeltaCompressionDotNet.MsDelta.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\DeltaCompressionDotNet.MsDelta.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\DeltaCompressionDotNet.PatchApi.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\DeltaCompressionDotNet.PatchApi.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Google.Apis.Auth.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Google.Apis.Auth.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Google.Apis.Auth.PlatformServices.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Google.Apis.Auth.PlatformServices.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Google.Apis.Blogger.v3.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Google.Apis.Blogger.v3.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Google.Apis.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Google.Apis.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Google.Apis.Core.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Google.Apis.Core.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Google.Apis.PlatformServices.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Google.Apis.PlatformServices.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\log4net.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\log4net.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\ICSharpCode.SharpZipLib.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\ICSharpCode.SharpZipLib.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Microsoft.Threading.Tasks.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Microsoft.Threading.Tasks.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Microsoft.Threading.Tasks.Extensions.Desktop.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Microsoft.Threading.Tasks.Extensions.Desktop.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Mono.Cecil.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Mono.Cecil.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Microsoft.Threading.Tasks.Extensions.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Microsoft.Threading.Tasks.Extensions.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Mono.Cecil.Mdb.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Mono.Cecil.Mdb.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Mono.Cecil.Pdb.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Mono.Cecil.Pdb.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Mono.Cecil.Rocks.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Mono.Cecil.Rocks.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Newtonsoft.Json.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Newtonsoft.Json.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\NuGet.Squirrel.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\NuGet.Squirrel.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.BlogClient.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.BlogClient.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.BrowserControl.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.BrowserControl.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Controls.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Controls.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.CoreServices.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.CoreServices.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.exe to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.exe.config to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe.config
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.exe.manifest to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe.manifest
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Extensibility.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Extensibility.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.FileDestinations.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.FileDestinations.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.HtmlEditor.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.HtmlEditor.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.HtmlParser.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.HtmlParser.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.InternalWriterPlugin.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.InternalWriterPlugin.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Interop.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Interop.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Interop.Mshtml.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Interop.Mshtml.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Interop.SHDocVw.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Interop.SHDocVw.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Localization.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Localization.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Mshtml.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Mshtml.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.PostEditor.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.PostEditor.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Ribbon.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Ribbon.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Splat.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Splat.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Squirrel.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Squirrel.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\System.Net.Http.Extensions.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\System.Net.Http.Extensions.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\System.Net.Http.Primitives.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\System.Net.Http.Primitives.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\Zlib.Portable.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\Zlib.Portable.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.Api.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Api.dll
2015-12-21 03:08:03> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\lib\net451\OpenLiveWriter.ApplicationFramework.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.ApplicationFramework.dll
2015-12-21 03:08:11> ApplyReleasesImpl: Squirrel Enabled Apps: []
2015-12-21 03:08:11> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2015-12-21 03:08:12> ApplyReleasesImpl: About to create shortcuts for OpenLiveWriter.exe, rootAppDir C:\Users\jason\AppData\Local\OpenLiveWriter
2015-12-21 03:08:25> ApplyReleasesImpl: Creating shortcut for OpenLiveWriter.exe => C:\Users\jason\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Open Live Writer\Open Live Writer.lnk
2015-12-21 03:08:26> ApplyReleasesImpl: About to save shortcut: C:\Users\jason\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Open Live Writer\Open Live Writer.lnk (target C:\Users\jason\AppData\Local\OpenLiveWriter\Update.exe, workingDir C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2, args --processStart OpenLiveWriter.exe)
2015-12-21 03:08:26> ApplyReleasesImpl: Creating shortcut for OpenLiveWriter.exe => C:\Users\jason\Desktop\Open Live Writer.lnk
2015-12-21 03:08:26> ApplyReleasesImpl: About to save shortcut: C:\Users\jason\Desktop\Open Live Writer.lnk (target C:\Users\jason\AppData\Local\OpenLiveWriter\Update.exe, workingDir C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2, args --processStart OpenLiveWriter.exe)
2015-12-21 03:08:26> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-12-21 03:08:28> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-12-21 03:08:28> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-12-21 03:08:28> ApplyReleasesImpl: Fixing up tray icons
2015-12-21 03:08:30> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2015-12-21 03:08:30> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2015-12-21 03:08:30> ApplyReleasesImpl: cleanDeadVersions: for version 0.5.1.2
2015-12-21 03:08:30> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.5.1.2
2015-12-21 03:10:06> Program: Starting Squirrel Updater: --install .
2015-12-21 03:10:06> Program: Starting install, writing to C:\Users\jason\AppData\Local\SquirrelTemp
2015-12-21 03:10:06> Program: About to install to: C:\Users\jason\AppData\Local\OpenLiveWriter
2015-12-21 03:10:06> Program: Install path C:\Users\jason\AppData\Local\OpenLiveWriter already exists, burning it to the ground
2015-12-21 03:10:06> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Api.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
2015-12-21 03:10:06> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Api.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.Api.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

ENDS

**Comment by avaikinius** [comment]
woops, tired, can't find file
