### ISSUE TITLE
Can't Publish Posts Containing Files

### ISSUE THREAD

**Issue by Indy27** [OpenLiveWriter/OpenLiveWriter#205]
Got this when I was posting something with file links

> The remote server returned an error: (403) Forbidden.

**Comment by kathweaver** [comment]
Can you give us more information:

What blog site were you using and can you add a log!  Thanks!

**Comment by Indy27** [comment]
Blogger.

Okay, so apparently closing and re-opening OLW seems to fix it, but I wonder why I had that when just 12 hours ago I did 2 posts with file links and they worked fine.

**Comment by kathweaver** [comment]
Can you give us logs, please.

**Comment by Indy27** [comment]
Well, it just did it again. Maybe the problem can be found here?

>Version: 0.5.1.2

OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\---\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe" 

Memory Load: 92%
Total Physical: 14318 MB
Available Physical: 1060 MB
Total Page File: 29828 MB
Available Page File: 4931 MB
Total Virtual: 2047 MB
Available Virtual: 1734 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


System.UnauthorizedAccessException: Access to the path 'C:\Users\Josh\AppData\Local\Temp\OpenLiveWriter1401189033\supfiles3BC1E807' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at OpenLiveWriter.CoreServices.TempFileManager.CreateNewFile(String dir, String pattern, Boolean asDir)
   at OpenLiveWriter.CoreServices.TempFileManager.CreateTempDir(String pattern)
   at OpenLiveWriter.PostEditor.BlogPostSupportingFileStorage..ctor()
   at OpenLiveWriter.PostEditor.BlogPostEditingContext.get_SupportingFileStorage()
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.EditPost(IBlogPostEditingContext editingContext, Boolean forceDirty)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace()
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e)

**Comment by ScottIsAFool** [comment]
Is this the same underlying problem as #26 I wonder.

**Comment by Indy27** [comment]
Dunno, this is for posting. I DO know more detail. It occurs if you're posting something with hotlinkable images (haven't tried posting w/ image not linked) instead of files. I tried publishing a post with linked image removed and was able to publish.

**Comment by martinwoodward** [comment]
@Indy27 - are you still having this issue with 0.5.1.3?

**Comment by Indy27** [comment]
Just installed 0.5.1.3 after dealing with another problem (it'll be up on a seperate thread) I've been busy all day so I'll try and post some more later tonight, see if it's gone or not.

**Comment by ScottIsAFool** [comment]
@Indy27 are you still seeing this?

**Comment by nvella** [comment]
I'll close this issue for now as the underlying issue seems to be the same as issue #26, which has since been fixed. Please don't hesitate to get back in touch if you're still experiencing this bug; I'll reopen the issue. Cheers 👍
