### ISSUE TITLE
ArgumentNullException With Blogger

### ISSUE THREAD

**Issue by Cheeks194th** [OpenLiveWriter/OpenLiveWriter#221]
I help manage 2 blogs with separate logins for each. With OLW I am able to create an account and connect, pull past blogs etc. The other account is able to be created but I get the following error when trying to pull blogs from blogger. 

System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ConvertToBlogPost(Post post)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.<>c.<GetRecentPosts>b__38_0(Post p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

I did try to verify settings between both accounts and by what I can tell, everything is the same. Any ideas?

Thanks for your help.
Corey

**Comment by willduff** [comment]
Fixed with pull request #222. This will be included in the next official release.

**Comment by martinwoodward** [comment]
FYI - pushed out a 0.5.1.4 to include this fix as a lot of people where hitting it.  To force an update download a new version from http://openlivewriter.org
