### ISSUE TITLE
Can't Get Posts List

### ISSUE THREAD

**Issue by nelsonkodama** [OpenLiveWriter/OpenLiveWriter#236]
Hi, guys,

I use Blogger, and I'm trying to get the posts list but I can't. 

I've downloaded version 0.5.1.3.

![image](https://cloud.githubusercontent.com/assets/16329205/11982975/00eb89e4-a997-11e5-9a7b-1d8866312375.png)

System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ConvertToBlogPost(Post post)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.<>c.<GetRecentPosts>b__38_0(Post p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment]
Thanks for reporting this, there is a fix in place and will be available when we next push an update. Dupe #221

**Comment by ScottIsAFool** [comment]
We have just pushed an update out (0.5.1.4) which fixes this. You can download it from http://openlivewriter.org.
