### ISSUE TITLE
Security compatibility with CloudFlare

### ISSUE THREAD

**Issue by jdhitsolutions** [OpenLiveWriter/OpenLiveWriter#257]
I ran into a problem posting to a Wordpress site I write for. I initially was getting access denied errors from the xmlrpc.php link. Although using the blog template in Word which uses the same account information worked fine. According to the security people on the site, Cloudflare rejected the LiveWriter agent headers as being associated with bots. They also mentioned that the posting attempt lit up over 20 XSS and SQL Injection rules. I suspect there is plenty of legacy code that is problematic for current platforms, hence this project. I'm not sure what I can do beyond reporting this but I might try to configure Cloudflare on my own Wordpress site and see if I can get any more details.

**Comment by kathweaver** [comment]
Can you send us a log:  it's in %localappdata%\OpenLiveWriter

You can also get to it by clicking on the File Tab, Clicking on About, and at the bottom click on Show Log File.  

Thanks!

**Comment by jdhitsolutions** [comment]
The problem is with https://www.petri.com/xmlrpc.php
I no longer have CloudFlare on my own blog so I can't test anything else.

[Open Live Writer log.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/74913/Open.Live.Writer.log.txt)

**Comment by willduff** [comment]
Below is the relevant part of your log file. It looks like CloudFlare sent back a Google Captcha for you to fill out and prove you are a human. It does make sense that CloudFlare thought the payload might be XSS/SQLi because it contained lots of escaped HTML. Thanks for reporting this, we may need to add in some special code to show the response to the user and have them fill out the Google Captcha if this is a widespread problem.

```
OpenLiveWriter,1.10592,None,00144,29-Dec-2015 10:46:56.705,"XML-RPC request:
https://www.petri.com/xmlrpc.php
<?xml version=""1.0"" encoding=""utf-8""?>
<methodCall>
 <methodName>metaWeblog.newPost</methodName>
 <params>
  <param>
   <value>
    <string>1</string>
   </value>
  </param>
  <param>
   <value>
    <string>JeffHicks</string>
   </value>
  </param>
  <param>
   <value>[removed]</value>
  </param>
  <param>
   <value>
    <struct>
     <member>
      <name>title</name>
      <value>
       <string>Creating Active Directory OUs with PowerShell</string>
      </value>
     </member>
     <member>
      <name>description</name>
      <value>
       <string>&lt;p&gt;Normally, I think of using PowerShell for ongoing and repetitive tasks. Using PowerShell scripts and tools creates a more efficient work environment. For tasks that you rarely do or only need to do once, it typically doesn't make sense to invest time in building a PowerShell-based solution, especially if doing the task manually isn't that complicated. To my mind, creating an Active Directory organizational unit, or OU, falls into that category. It is rather trivial to open up Active Directory Users and Computers and create a new OU.&lt;/p&gt; &lt;p&gt;So why use PowerShell? One scenario would be for quickly building a test environment including an Active Directory domain. With a PowerShell script you can create hundreds of OUs in seconds. Another scenario that I can think of is as a change control mechanism. Instead of manually creating a new OU in the traditional manner, spend a little extra time creating a PowerShell script to do it. This script can be reviewed, tested and include as much documentation in the form of comments as you need.&amp;nbsp; The script becomes a resource document or artifact that indicates what was done and why. It may only be a few lines of PowerShell commands but it serves as a record. So how do we do this?&lt;/p&gt; &lt;p&gt;For starters you need the most current version of the Remote Server Administration Tools (RSAT) for your desktop. Everything I'm going to show you can be, and should be, accomplished from your admin desktop. There is no need to logon to a server. When you configure RSAT, make sure you include the Active Directory PowerShell module. &lt;/p&gt; &lt;p&gt;For now, I'm going to assume you are running your PowerShell session with credentials that have permissions to create an OU. The cmdlet, New-ADOrganizationalUnit, is pretty straightforward.&lt;/p&gt; &lt;p&gt;&amp;nbsp;&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-3.png""&gt;&lt;img title=""New-ADOrganizationalUnit Help (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""New-ADOrganizationalUnit Help (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-3.png"" width=""644"" height=""379""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;All you need to do is specify the name of the new OU.&lt;/p&gt; &lt;p&gt;New-ADOrganizationalUnit -Name ""Petri Users""&lt;br&gt;By default, PowerShell will create the OU off of the domain root. You can use PowerShell to get the newly created OU.&lt;/p&gt; &lt;p&gt;Get-ADOrganizationalUnit -Identity ""OU=Petri Users,DC=globomantics,DC=Local""&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-4.png""&gt;&lt;img title=""Getting the new OU (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""Getting the new OU (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-4.png"" width=""644"" height=""222""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;Here's the new OU in Active Directory Users and Computers.&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-5.png""&gt;&lt;img title=""The new OU in ADUC (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""The new OU in ADUC (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-5.png"" width=""497"" height=""484""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;By default, the cmdlet doesn't write anything to the pipeline unless you use –Passthru. And if you want to create the OU in a location other than the domain root, you need to specify the distinguished name of the parent container.&lt;/p&gt; &lt;p&gt;New-ADOrganizationalUnit -Name Vendors -Path ""OU=Employees,DC=Globomantics,DC=Local"" -Description ""Temporary vendor accounts"" -PassThru&lt;br&gt;&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-6.png""&gt;&lt;img title=""Creating an OU in an alternate location (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""Creating an OU in an alternate location (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-6.png"" width=""644"" height=""193""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;Let's say that you need to create many OUs. If you look at help for New-ADOrganizationalUnit you'll see that many of the parameters can be passed by property name. This means if you pipe in an object with a matching property name, the PowerShell will assign that value to the corresponding parameter.&lt;/p&gt; &lt;p&gt;The benefit is that I can take a spreadsheet like this:&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-7.png""&gt;&lt;img title=""Office locations (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""Office locations (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-7.png"" width=""644"" height=""346""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;Notice that the column headings correspond to parameter names. While you could write code to read the Excel spreadsheet, it is much easier to export to a CSV and use that within PowerShell.&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-8.png""&gt;&lt;img title=""Testing the location CSV file (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""Testing the location CSV file (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-8.png"" width=""644"" height=""242""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;I can test using –Whatif which is important because some of the locations are child OUs and I need to make sure the parents are created first.&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-9.png""&gt;&lt;img title=""Testing new OUs with Whatif (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""Testing new OUs with Whatif (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-9.png"" width=""644"" height=""188""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;If I am satisfied, I can run the command to create the OU structure.&lt;/p&gt; &lt;p&gt;import-csv s:\offices.csv | New-ADOrganizationalUnit –PassThru&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-10.png""&gt;&lt;img title=""Creating new OUs from a CSV file (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""Creating new OUs from a CSV file (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-10.png"" width=""644"" height=""318""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;Within a matter of seconds I created 15 new organizational units where I needed them and properly configured. Here's the final result in Active Directory Users and Computers:&lt;/p&gt; &lt;p&gt;&lt;a href=""https://www.petri.com/wp-content/uploads/2015/12/image-11.png""&gt;&lt;img title=""New OUs (Image Credit: Jeff Hicks)"" style=""border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px"" border=""0"" alt=""New OUs (Image Credit: Jeff Hicks)"" src=""https://www.petri.com/wp-content/uploads/2015/12/image_thumb-11.png"" width=""644"" height=""419""&gt;&lt;/a&gt;&lt;/p&gt; &lt;p&gt;In the next article, we'll explore ways of modifying and removing OUs. In the meantime, I hope you'll fire up your test environment and try these commands out. Need a test AD, go ahead and create one and let me know how it goes.&lt;/p&gt;</string>
      </value>
     </member>
     <member>
      <name>mt_text_more</name>
      <value>
       <string />
      </value>
     </member>
     <member>
      <name>mt_keywords</name>
      <value>
       <string>Active Directory, Intermediate</string>
      </value>
     </member>
     <member>
      <name>wp_slug</name>
      <value>
       <string />
      </value>
     </member>
     <member>
      <name>mt_basename</name>
      <value>
       <string />
      </value>
     </member>
     <member>
      <name>wp_password</name>
      <value>
       <string />
      </value>
     </member>
     <member>
      <name>categories</name>
      <value>
       <array>
        <data>
         <value>
          <string>Active Directory</string>
         </value>
         <value>
          <string>PowerShell</string>
         </value>
        </data>
       </array>
      </value>
     </member>
     <member>
      <name>mt_excerpt</name>
      <value>
       <string />
      </value>
     </member>
     <member>
      <name>mt_tb_ping_urls</name>
      <value>
       <string>(comma separated)</string>
      </value>
     </member>
    </struct>
   </value>
  </param>
  <param>
   <value>
    <boolean>0</boolean>
   </value>
  </param>
 </params>
</methodCall>",""
OpenLiveWriter,1.10592,None,00145,29-Dec-2015 10:46:56.705,"== BEGIN WebException =====================",""
OpenLiveWriter,1.10592,None,00146,29-Dec-2015 10:46:56.705,"Status: ProtocolError",""
OpenLiveWriter,1.10592,None,00147,29-Dec-2015 10:46:56.705,"System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SendRequest(String requestUri, HttpRequestFilter filter)
   at OpenLiveWriter.CoreServices.XmlRpcClient.CallMethod(String methodName, XmlRpcValue[] parameters)
   at OpenLiveWriter.BlogClient.Clients.XmlRpcBlogClient.CallMethod(String methodName, XmlRpcValue[] parameters)",""
OpenLiveWriter,1.10592,None,00148,29-Dec-2015 10:46:56.705,"HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Connection: close
X-Frame-Options: SAMEORIGIN
CF-RAY: 25c6a401782021fe-EWR
Content-Type: text/html; charset=UTF-8
Date: Tue, 29 Dec 2015 15:46:56 GMT
Set-Cookie: __cfduid=d19b66aa188d4a71722327d99955462d91451404016; expires=Wed, 28-Dec-16 15:46:56 GMT; path=/; domain=.petri.com; HttpOnly
Server: cloudflare-nginx

<!DOCTYPE html>
<!--[if lt IE 7]> <html class=""no-js ie6 oldie"" lang=""en-US""> <![endif]-->
<!--[if IE 7]>    <html class=""no-js ie7 oldie"" lang=""en-US""> <![endif]-->
<!--[if IE 8]>    <html class=""no-js ie8 oldie"" lang=""en-US""> <![endif]-->
<!--[if gt IE 8]><!--> <html class=""no-js"" lang=""en-US""> <!--<![endif]-->
<head>
<title>Attention Required! | CloudFlare</title>
<meta charset=""UTF-8"" />
<meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-8"" />
<meta http-equiv=""X-UA-Compatible"" content=""IE=Edge,chrome=1"" />
<meta name=""robots"" content=""noindex, nofollow"" />
<meta name=""viewport"" content=""width=device-width,initial-scale=1,maximum-scale=1"" />
<link rel=""stylesheet"" id=""cf_styles-css"" href=""/cdn-cgi/styles/cf.errors.css"" type=""text/css"" media=""screen,projection"" />
<!--[if lt IE 9]><link rel=""stylesheet"" id='cf_styles-ie-css' href=""/cdn-cgi/styles/cf.errors.ie.css"" type=""text/css"" media=""screen,projection"" /><![endif]-->
<style type=""text/css"">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type=""text/javascript"" src=""/cdn-cgi/scripts/jquery.min.js""></script><![endif]-->
<!--[if gte IE 10]><!--><script type=""text/javascript"" src=""/cdn-cgi/scripts/zepto.min.js""></script><!--<![endif]-->
<script type=""text/javascript"" src=""/cdn-cgi/scripts/cf.common.js""></script>


</head>
<body>
  <div id=""cf-wrapper"">
    <div class=""cf-alert cf-alert-error cf-cookie-error"" id=""cookie-alert"" data-translate=""enable_cookies"">Please enable cookies.</div>
    <div id=""cf-error-details"" class=""cf-error-details-wrapper"">
      <div class=""cf-wrapper cf-header cf-error-overview"">
        <h1 data-translate=""challenge_headline"">One more step</h1>
        <h2 class=""cf-subheadline""><span data-translate=""complete_sec_check"">Please complete the security check to access</span> petri.com</h2>
      </div><!-- /.header -->

      <div class=""cf-section cf-highlight cf-captcha-container"">
        <div class=""cf-wrapper"">
          <div class=""cf-columns two"">
            <div class=""cf-column"">
              <div class=""cf-highlight-inverse cf-form-stacked"">
                <form class=""challenge-form"" id=""challenge-form"" action=""/xmlrpc.php?__cf_waf_tk__=0568990081tlW8c4Vq7FMKZxBR27qFYXxAos"" method=""post"" enctype=""application/x-www-form-urlencoded"">
<script type=""text/javascript"" src=""/cdn-cgi/scripts/cf.challenge.js"" data-type=""normal""  data-ray=""25c6a401782021fe"" async></script>
<noscript id=""cf-captcha-bookmark"" class=""cf-captcha-info"">
  <iframe src=""//www.google.com/recaptcha/api/noscript?k=6LeT6gcAAAAAAAZ_yDmTMqPH57dJQZdQcu6VFqog"" height=""300"" width=""500"" frameborder=""0""></iframe>
  <input type=""hidden"" name=""recaptcha_response_field"" value=""manual_challenge"">
  <label for=""manual_recaptcha_challenge_field"">Enter confirmation code after solving challenge above</label>
  <textarea id=""manual_recaptcha_challenge_field"" name=""recaptcha_challenge_field"" rows=""3"" cols=""40""></textarea>
  <button type=""submit"" class=""cf-btn cf-btn-accept""><span data-translate=""submit"">Submit</span></button>
</noscript>
</form>

              </div>
            </div>

            <div class=""cf-column"">
              <div class=""cf-screenshot-container"">
              
                <span class=""cf-no-screenshot""></span>
              
              </div>
            </div>
          </div><!-- /.columns -->
        </div>
      </div><!-- /.captcha-container -->

      <div class=""cf-section cf-wrapper"">
        <div class=""cf-columns two"">
          <div class=""cf-column"">
            <h2 data-translate=""why_captcha_headline"">Why do I have to complete a CAPTCHA?</h2>

            <p data-translate=""why_captcha_detail"">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class=""cf-column"">
            <h2 data-translate=""resolve_captcha_headline"">What can I do to prevent this in the future?</h2>

            <p data-translate=""resolve_captcha_antivirus"">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate=""resolve_captcha_network"">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class=""cf-error-footer cf-wrapper"">
  <p>
    <span class=""cf-footer-item"">CloudFlare Ray ID: <strong>25c6a401782021fe</strong></span>
    <span class=""cf-footer-separator"">&bull;</span>
    <span class=""cf-footer-item""><span data-translate=""your_ip"">Your IP</span>: 96.249.48.81</span>
    <span class=""cf-footer-separator"">&bull;</span>
    <span class=""cf-footer-item""><span data-translate=""performance_security_by"">Performance &amp; security by</span> <a data-orig-proto=""https"" data-orig-ref=""www.cloudflare.com/5xx-error-landing?utm_source=error_footer"" id=""brand_link"" target=""_blank"">CloudFlare</a></span>
    
    <span class=""cf-footer-separator"">&bull;</span>
    <span class=""cf-footer-item"">
      <select id=""lang-selector"">
        <option value="""">Select a Language</option>
        <option value=""en"">English</option>
        <option value=""es"">Español</option>
      </select>
    </span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type=""text/javascript"">
  window._cf_translation = {};
  window._cf_translation.locale = 'en';
  window._cf_translation.blobs = {};
</script>

</body>
</html>

",""
OpenLiveWriter,1.10592,None,00149,29-Dec-2015 10:46:56.705,"== END WebException =======================",""
OpenLiveWriter,1.10592,Fail,00150,29-Dec-2015 10:46:56.718,"OpenLiveWriter.Extensibility.BlogClient.BlogClientHttpErrorException: Server Error - The server reported an error with the following web address:

https://www.petri.com/xmlrpc.php

403 Forbidden
   at OpenLiveWriter.BlogClient.Clients.XmlRpcBlogClient.CallMethod(String methodName, XmlRpcValue[] parameters)
   at OpenLiveWriter.BlogClient.Clients.MetaweblogClient.MetaweblogNewPost(String blogId, BlogPost post, Boolean publish)
   at OpenLiveWriter.BlogClient.Clients.MetaweblogClient.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.BlogClient.Clients.XmlRpcBlogClient.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()","   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at OpenLiveWriter.CoreServices.Diagnostics.LogFileTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.UpdateWeblog(Boolean publish)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.PostToWeblog(Boolean publish)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.commandPostAsDraft_Execute(Object sender, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.OnExecute(EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.PerformExecute()
   at OpenLiveWriter.ApplicationFramework.Command.PerformExecute(CommandExecutionVerb verb, PropertyKeyRef key, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
   at OpenLiveWriter.ApplicationFramework.CommandManager.Execute(UInt32 commandId, CommandExecutionVerb verb, PropertyKeyRef key, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.Launcher.ThreadMain(Object[] parameters)
   at OpenLiveWriter.CoreServices.Threading.ThreadStartWithParams.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()"

```

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
