### ISSUE TITLE
Setup.exe Null String?

### ISSUE THREAD

**Issue by donmalpas** [OpenLiveWriter/OpenLiveWriter#285]
Monday, January 04, 2016 2:18:52 PM

Version: 0.5.1.4

OS Version: Microsoft Windows NT 6.2.9200.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\Bogey\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 71%
Total Physical: 1023 MB
Available Physical: 286 MB
Total Page File: 2751 MB
Available Page File: 1865 MB
Total Virtual: 2047 MB
Available Virtual: 1676 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.PostHtmlEditingSettings.GetEditorTemplateHtml(BlogEditingTemplateType templateType, Boolean forceRTL)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.EditingTemplateLoader.LoadBlogTemplate(String blogId, BlogEditingTemplateType templateType, Boolean forceRTL)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.GetPreviewHtml()
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.Initialize(IBlogPostEditingContext editingContext, IBlogClientOptions clientOptions)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OnBlogPostChanged()
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.EditPost(IBlogPostEditingContext editingContext, Boolean forceDirty)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace()
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e)

**Comment by donmalpas** [comment]
Forgot to say this is Win10

**Comment by hashhar** [comment]
Can you tell us the path to your `Users\youruser\AppData` folder? It seems likely that there are some characters in that path which are causing the issue.

**Comment by donmalpas** [comment]
If I understand the question correctly, the path is
c:\users\bogey\appdata\local\windowslivewriter

Attaching the log file located in that folder.

The event occurs on startup.

Cheers Don          
dmalpas@gmail.com

**Comment by nvella** [comment]
For anyone looking into this, it could be worth investigating `GetEditorTemplateHtml`. From what I gather, this has nothing to do with setup, but rather a path we are passing into `System.IO.Path.GetFileName`. Maybe some string sanitation needs to be put into place.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
