### ISSUE TITLE
OLW crashes immeadiately on opening

### ISSUE THREAD

**Issue by Phibber-McGee** [OpenLiveWriter/OpenLiveWriter#289]
Win 10.
Brand new install of OLW. Crashes the moment it opens.

![capture olw crash](https://cloud.githubusercontent.com/assets/16563845/12124745/cb1940a2-b3ac-11e5-9e69-630e21d21653.JPG)

**Comment by ScottIsAFool** [comment]
Could you please post your log file. This can be found in %localappdata%\OpenLiveWriter

**Comment by Phibber-McGee** [comment]
Thanks for helping here it is:

OpenLiveWriter,1.8272,None,00001,05-Jan-2016 12:33:27.439,"Migrating user settings...",""
OpenLiveWriter,1.8272,None,00002,05-Jan-2016 12:33:27.486,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,1.8272,None,00003,05-Jan-2016 12:33:27.486,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.8272,None,00004,05-Jan-2016 12:33:28.439,"Failed to load blog settings for: ",""
OpenLiveWriter,1.8272,None,00005,05-Jan-2016 12:33:28.455,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.8272,None,00006,05-Jan-2016 12:35:51.454,"Timed out while loading blog homepage for theme detection.",""
OpenLiveWriter,1.8272,None,00007,05-Jan-2016 12:37:33.124,"Timed out while loading blog homepage for theme detection.",""
OpenLiveWriter,1.8272,None,00008,05-Jan-2016 12:42:42.036,"Dumping file registration for category Recent drafts in response to jumplist error:",""
OpenLiveWriter,1.8272,None,00009,05-Jan-2016 12:42:42.036,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\Leprechaun Laughs 01 06 2016.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\Leprechaun Laughs 01 06 2016.wpost",""
OpenLiveWriter,1.8272,None,00010,05-Jan-2016 12:42:42.036,"Dumping file registration for extension: .wpost",""
OpenLiveWriter,1.8272,None,00011,05-Jan-2016 12:42:42.036,"HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.wpost",""
OpenLiveWriter,1.8272,None,00012,05-Jan-2016 12:42:42.036,"Default Value: WindowsLiveWriter.Post.1",""
OpenLiveWriter,1.8272,None,00013,05-Jan-2016 12:42:42.036,"Name: Content Type --> Value: application/x-wpost",""
OpenLiveWriter,1.8272,None,00014,05-Jan-2016 12:42:42.036,"  HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.wpost\PersistentHandler",""
OpenLiveWriter,1.8272,None,00015,05-Jan-2016 12:42:42.036,"  Default Value: {8C8C66D8-ADD6-4a80-BF17-CB1494102876}",""
OpenLiveWriter,1.8272,None,00016,05-Jan-2016 12:42:42.036,"  HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.wpost\WindowsLiveWriter.Post.1",""
OpenLiveWriter,1.8272,None,00017,05-Jan-2016 12:42:42.036,"Dumping ProgId for extension: .wpost",""
OpenLiveWriter,1.8272,None,00018,05-Jan-2016 12:42:42.036,"HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WindowsLiveWriter.Post.1",""
OpenLiveWriter,1.8272,None,00019,05-Jan-2016 12:42:42.036,"Default Value: Windows Live Writer Post",""
OpenLiveWriter,1.8272,None,00020,05-Jan-2016 12:42:42.036,"Name: AppUserModelID --> Value: Windows Live Writer - {33CFF92E-5CC9-43c8-B4EE-B5501A6FC53F}",""
OpenLiveWriter,1.8272,None,00021,05-Jan-2016 12:42:42.036,"  HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WindowsLiveWriter.Post.1\DefaultIcon",""
OpenLiveWriter,1.8272,None,00022,05-Jan-2016 12:42:42.036,"  Default Value: C:\Program Files (x86)\Windows Live\Writer\WeblogPost.ico",""
OpenLiveWriter,1.8272,None,00023,05-Jan-2016 12:42:42.036,"  HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WindowsLiveWriter.Post.1\shell",""
OpenLiveWriter,1.8272,None,00024,05-Jan-2016 12:42:42.036,"    HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WindowsLiveWriter.Post.1\shell\open",""
OpenLiveWriter,1.8272,None,00025,05-Jan-2016 12:42:42.036,"    Default Value: Open",""
OpenLiveWriter,1.8272,None,00026,05-Jan-2016 12:42:42.036,"      HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WindowsLiveWriter.Post.1\shell\open\command",""
OpenLiveWriter,1.8272,None,00027,05-Jan-2016 12:42:42.036,"      Default Value: ""C:\Program Files (x86)\Windows Live\Writer\WindowsLiveWriter.exe"" ""%1""",""
OpenLiveWriter,1.8272,Fail,00028,05-Jan-2016 12:42:42.224,"ERROR: Incorrect AppUserModelID for WindowsLiveWriter.Post.1: Windows Live Writer - {33CFF92E-5CC9-43c8-B4EE-B5501A6FC53F}","   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at OpenLiveWriter.CoreServices.Diagnostics.LogFileTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at OpenLiveWriter.PostEditor.JumpList.JumpList.DumpFileRegistration(JumpListCustomCategory category)
   at OpenLiveWriter.PostEditor.JumpList.JumpList.AppendCustomCategories()
   at OpenLiveWriter.PostEditor.JumpList.JumpList.Refresh()
   at OpenLiveWriter.PostEditor.JumpList.WriterJumpList.Invalidate(IntPtr ownerWindow)
   at OpenLiveWriter.ApplicationLauncher.CreateInitialProfile(IDisposable splashScreen)
   at OpenLiveWriter.ApplicationLauncher.EnsureBloggingConfigured(IDisposable splashScreen)
   at OpenLiveWriter.ApplicationLauncher.LaunchBloggingForm(String[] args, IDisposable splashScreen, Boolean isFirstInstance)
   at OpenLiveWriter.ApplicationMain.LaunchFirstInstance(IDisposable splashScreen, String[] args)
   at OpenLiveWriter.ApplicationMain.LaunchAction(String[] args, Boolean isFirstInstance)
   at OpenLiveWriter.CoreServices.SingleInstanceApplicationManager.Run(String appId, LaunchAction action, String[] args)
   at OpenLiveWriter.ApplicationMain.Main(String[] args)"
OpenLiveWriter,1.8272,None,00029,05-Jan-2016 12:42:42.224,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL LL Digital Media Christmas 2015 Edition.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL LL Digital Media Christmas 2015 Edition.wpost",""
OpenLiveWriter,1.8272,None,00030,05-Jan-2016 12:42:42.224,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL LL Digital Media Thanksgiving 2015 Special Edition.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL LL Digital Media Thanksgiving 2015 Special Edition.wpost",""
OpenLiveWriter,1.8272,None,00031,05-Jan-2016 12:42:42.224,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL-LL Special Mini Roast Edition- Happy Birthday  PaulK9.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL-LL Special Mini Roast Edition- Happy Birthday  PaulK9.wpost",""
OpenLiveWriter,1.8272,None,00032,05-Jan-2016 12:42:42.224,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL LL Digital Media Veteran’s Day 2015 Special Edition.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\DL LL Digital Media Veteran’s Day 2015 Special Edition.wpost",""
OpenLiveWriter,1.8272,None,00033,05-Jan-2016 12:42:42.224,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\16 MYSTERIOUS Photos That Should Not Exist.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\16 MYSTERIOUS Photos That Should Not Exist.wpost",""
OpenLiveWriter,1.8272,None,00034,05-Jan-2016 12:42:42.224,"JumpListItem: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\Leprechaun Laughs # 317 for Wednesday Sept.wpost with path: C:\Users\Jeff\Documents\My Weblog Posts\Drafts\Leprechaun Laughs # 317 for Wednesday Sept.wpost",""
OpenLiveWriter,1.8272,Fail,00035,05-Jan-2016 12:42:42.271,"System.InvalidOperationException: The file type is not registered with this application.
   at OpenLiveWriter.PostEditor.JumpList.JumpList.AppendCustomCategories()
   at OpenLiveWriter.PostEditor.JumpList.JumpList.Refresh()
   at OpenLiveWriter.PostEditor.JumpList.WriterJumpList.Invalidate(IntPtr ownerWindow)","   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at OpenLiveWriter.CoreServices.Diagnostics.LogFileTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at OpenLiveWriter.PostEditor.JumpList.WriterJumpList.Invalidate(IntPtr ownerWindow)
   at OpenLiveWriter.ApplicationLauncher.CreateInitialProfile(IDisposable splashScreen)
   at OpenLiveWriter.ApplicationLauncher.EnsureBloggingConfigured(IDisposable splashScreen)
   at OpenLiveWriter.ApplicationLauncher.LaunchBloggingForm(String[] args, IDisposable splashScreen, Boolean isFirstInstance)
   at OpenLiveWriter.ApplicationMain.LaunchFirstInstance(IDisposable splashScreen, String[] args)
   at OpenLiveWriter.ApplicationMain.LaunchAction(String[] args, Boolean isFirstInstance)
   at OpenLiveWriter.CoreServices.SingleInstanceApplicationManager.Run(String appId, LaunchAction action, String[] args)
   at OpenLiveWriter.ApplicationMain.Main(String[] args)"
OpenLiveWriter,1.8272,None,00036,05-Jan-2016 12:42:42.302,"Failed to load blog settings for: ",""
OpenLiveWriter,1.8272,None,00037,05-Jan-2016 12:42:42.302,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.8272,None,00038,05-Jan-2016 12:42:44.302,"499 499",""
OpenLiveWriter,1.8272,None,00039,05-Jan-2016 12:42:44.443,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(a573bcd3-a96e-4cf2-98fb-e9f8b2541643)",""
OpenLiveWriter,1.8272,None,00040,05-Jan-2016 12:42:45.476,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.8272,None,00041,05-Jan-2016 12:42:45.491,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.8272,None,00042,05-Jan-2016 12:42:45.976,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.8272,None,00043,05-Jan-2016 12:42:45.976,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.7224,None,00001,05-Jan-2016 12:43:13.315,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,1.7224,None,00002,05-Jan-2016 12:43:13.315,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.7224,None,00003,05-Jan-2016 12:43:13.955,"499 499",""
OpenLiveWriter,1.7224,None,00004,05-Jan-2016 12:43:14.127,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(a573bcd3-a96e-4cf2-98fb-e9f8b2541643)",""
OpenLiveWriter,1.7224,None,00005,05-Jan-2016 12:43:14.815,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.7224,None,00006,05-Jan-2016 12:43:14.815,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.7224,None,00007,05-Jan-2016 12:43:18.089,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.7224,None,00008,05-Jan-2016 12:43:18.089,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.10072,None,00001,05-Jan-2016 12:43:28.562,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,1.10072,None,00002,05-Jan-2016 12:43:28.562,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.10072,None,00003,05-Jan-2016 12:43:29.206,"499 499",""
OpenLiveWriter,1.10072,None,00004,05-Jan-2016 12:43:29.331,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(a573bcd3-a96e-4cf2-98fb-e9f8b2541643)",""
OpenLiveWriter,1.10072,None,00005,05-Jan-2016 12:43:30.456,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.10072,None,00006,05-Jan-2016 12:43:30.456,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.1308,None,00001,05-Jan-2016 12:43:40.539,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,1.1308,None,00002,05-Jan-2016 12:43:40.539,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.1308,None,00003,05-Jan-2016 12:43:41.150,"499 499",""
OpenLiveWriter,1.1308,None,00004,05-Jan-2016 12:43:41.321,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(a573bcd3-a96e-4cf2-98fb-e9f8b2541643)",""
OpenLiveWriter,1.1308,None,00005,05-Jan-2016 12:43:41.900,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.1308,None,00006,05-Jan-2016 12:43:41.900,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.1308,None,00007,05-Jan-2016 12:43:44.589,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.1308,None,00008,05-Jan-2016 12:43:44.589,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.7020,None,00001,05-Jan-2016 12:52:20.065,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,1.7020,None,00002,05-Jan-2016 12:52:20.065,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.7020,None,00003,05-Jan-2016 12:52:20.722,"499 499",""
OpenLiveWriter,1.7020,None,00004,05-Jan-2016 12:52:20.878,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(a573bcd3-a96e-4cf2-98fb-e9f8b2541643)",""
OpenLiveWriter,1.7020,None,00005,05-Jan-2016 12:52:21.519,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.7020,None,00006,05-Jan-2016 12:52:21.519,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.7020,None,00007,05-Jan-2016 12:52:26.036,"Creating a readable ribbon istream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.7020,None,00008,05-Jan-2016 12:52:26.036,"Failed to create ribbon stream for C:\Users\Jeff\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002","

**Comment by cbtoolkit** [comment]
I'm having the exact same issue. I deleted my log and restarted - just to clean it up a bit. Below is the content of my log file as of last start and crash. Any help is appreciated.
============
OpenLiveWriter,1.7088,None,00001,06-Jan-2016 06:24:03.419,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,1.7088,None,00002,06-Jan-2016 06:24:03.419,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.7088,None,00003,06-Jan-2016 06:24:04.255,"499 499",""
OpenLiveWriter,1.7088,None,00004,06-Jan-2016 06:24:04.375,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(7cca11ed-7a32-4c99-b985-8fe3fff81cb0)",""
OpenLiveWriter,1.7088,None,00005,06-Jan-2016 06:24:04.823,"Creating a readable ribbon istream for C:\Users\matt_000\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.7088,None,00006,06-Jan-2016 06:24:04.823,"Failed to create ribbon stream for C:\Users\matt_000\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.7088,None,00007,06-Jan-2016 06:24:05.120,"Creating a readable ribbon istream for C:\Users\matt_000\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.7088,None,00008,06-Jan-2016 06:24:05.120,"Failed to create ribbon stream for C:\Users\matt_000\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""

**Comment by ponsaelius** [comment]
Having thr same issue on a surface pro.

**Comment by willduff** [comment]
Can you guys follow these [Instructions for viewing Writer problem reports](https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-viewing-Writer-problem-reports) and paste the full details into here? Thanks!

**Comment by cbtoolkit** [comment]
Odd.. it crashed whenever I tried it for about 2 days. Right now, it is running okay. Of course.. another issue I'm not sure how to fix. It identified my theme but I have a background image for the page. The background image is behind the content- does not obscure it. But, in the editor, it shows up at the top of the editor - and obscures the text I am typing. 

I don't see a place to edit without showing the formatting - which is not that important to me.

Any ideas?

**Comment by willduff** [comment]
@cbtoolkit You can click the **Blog Account** tab in the ribbon, and then click on **Blog theme** to toggle the theme to off.
![image](https://cloud.githubusercontent.com/assets/134678/12359530/a88a7c78-bb67-11e5-9e7c-0637ced2873d.png)

**Comment by cbtoolkit** [comment]
That worked. Thanks. I'll do some more testing and let you know what I experience.

**Comment by Phibber-McGee** [comment]
Will- 

In order to comply with your request the program would have to first open and run at all.

Perhaps you can explain to me exactly what part of ‘crashes immediately upon opening’
I am make too vague so as not to be understandable?

**Comment by willduff** [comment]
@Phibber-McGee Please take a look at the instructions I linked to previously: https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-viewing-Writer-problem-reports

You don't need to be able to launch Writer in order to get the 'problem reports'.

**Comment by nvella** [comment]
Hi @Phibber-McGee, I understand it's been a while. Would I be able to ask if you're still encountering this issue? Regards

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
