### ISSUE TITLE
win10 install failure + code dump

### ISSUE THREAD

**Issue by JA2025** [OpenLiveWriter/OpenLiveWriter#294]
NOOB ALERT

So, have no idea what I'm talking about, technically, but can report what happened when I clicked install on OLW ...

Clicked install, install failed, auto-generated fault report via text file, as below.

Workaround? Will try administrator right click install next.

2016-01-06 21:49:33> Program: Starting Squirrel Updater: --install .
2016-01-06 21:49:33> Program: Starting install, writing to C:\Users\jason\AppData\Local\SquirrelTemp
2016-01-06 21:49:34> Program: About to install to: C:\Users\jason\AppData\Local\OpenLiveWriter
2016-01-06 21:49:34> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-01-06 21:49:34> CheckForUpdateImpl: Reading RELEASES file from C:\Users\jason\AppData\Local\SquirrelTemp
2016-01-06 21:49:34> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-01-06 21:49:35> ApplyReleasesImpl: Writing files to app directory: C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\DeltaCompressionDotNet.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\DeltaCompressionDotNet.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\DeltaCompressionDotNet.MsDelta.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\DeltaCompressionDotNet.MsDelta.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\DeltaCompressionDotNet.PatchApi.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\DeltaCompressionDotNet.PatchApi.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Google.Apis.Auth.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Auth.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Google.Apis.Auth.PlatformServices.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Auth.PlatformServices.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Google.Apis.Blogger.v3.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Blogger.v3.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Google.Apis.Core.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Core.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Google.Apis.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Google.Apis.PlatformServices.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.PlatformServices.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\ICSharpCode.SharpZipLib.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\ICSharpCode.SharpZipLib.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\log4net.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\log4net.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Microsoft.Threading.Tasks.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Microsoft.Threading.Tasks.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Microsoft.Threading.Tasks.Extensions.Desktop.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Microsoft.Threading.Tasks.Extensions.Desktop.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Microsoft.Threading.Tasks.Extensions.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Microsoft.Threading.Tasks.Extensions.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Mono.Cecil.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Mono.Cecil.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Mono.Cecil.Mdb.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Mono.Cecil.Mdb.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Mono.Cecil.Pdb.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Mono.Cecil.Pdb.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Mono.Cecil.Rocks.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Mono.Cecil.Rocks.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Newtonsoft.Json.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Newtonsoft.Json.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\NuGet.Squirrel.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\NuGet.Squirrel.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Api.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Api.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.ApplicationFramework.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.ApplicationFramework.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.BlogClient.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.BlogClient.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.BrowserControl.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.BrowserControl.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Controls.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Controls.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.CoreServices.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.CoreServices.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.exe to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.exe
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.exe.config to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.exe.config
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.exe.manifest to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.exe.manifest
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Extensibility.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Extensibility.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.FileDestinations.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.FileDestinations.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.HtmlEditor.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.HtmlEditor.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Localization.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Localization.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.HtmlParser.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.HtmlParser.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Mshtml.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Mshtml.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.InternalWriterPlugin.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.InternalWriterPlugin.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.PostEditor.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.PostEditor.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Ribbon.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Ribbon.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Interop.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Interop.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Interop.Mshtml.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Interop.Mshtml.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Splat.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Splat.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\OpenLiveWriter.Interop.SHDocVw.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.Interop.SHDocVw.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Squirrel.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Squirrel.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\System.Net.Http.Extensions.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\System.Net.Http.Extensions.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\System.Net.Http.Primitives.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\System.Net.Http.Primitives.dll
2016-01-06 21:49:38> ApplyReleasesImpl: Moving file C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\lib\net451\Zlib.Portable.dll to C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Zlib.Portable.dll
2016-01-06 21:49:39> ApplyReleasesImpl: Squirrel Enabled Apps: []
2016-01-06 21:49:39> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2016-01-06 21:49:39> ApplyReleasesImpl: About to create shortcuts for OpenLiveWriter.exe, rootAppDir C:\Users\jason\AppData\Local\OpenLiveWriter
2016-01-06 21:49:41> ApplyReleasesImpl: Creating shortcut for OpenLiveWriter.exe => C:\Users\jason\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Open Live Writer\Open Live Writer.lnk
2016-01-06 21:49:42> ApplyReleasesImpl: About to save shortcut: C:\Users\jason\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Open Live Writer\Open Live Writer.lnk (target C:\Users\jason\AppData\Local\OpenLiveWriter\Update.exe, workingDir C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4, args --processStart OpenLiveWriter.exe)
2016-01-06 21:49:42> ApplyReleasesImpl: Creating shortcut for OpenLiveWriter.exe => C:\Users\jason\Desktop\Open Live Writer.lnk
2016-01-06 21:49:42> ApplyReleasesImpl: About to save shortcut: C:\Users\jason\Desktop\Open Live Writer.lnk (target C:\Users\jason\AppData\Local\OpenLiveWriter\Update.exe, workingDir C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4, args --processStart OpenLiveWriter.exe)
2016-01-06 21:49:42> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-01-06 21:49:42> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-01-06 21:49:42> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-01-06 21:49:42> ApplyReleasesImpl: Fixing up tray icons
2016-01-06 21:49:42> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-01-06 21:49:42> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-01-06 21:49:42> ApplyReleasesImpl: cleanDeadVersions: for version 0.5.1.4
2016-01-06 21:49:42> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.5.1.4
2016-01-06 21:50:36> Program: Starting Squirrel Updater: --install .
2016-01-06 21:50:36> Program: Starting install, writing to C:\Users\jason\AppData\Local\SquirrelTemp
2016-01-06 21:50:36> Program: About to install to: C:\Users\jason\AppData\Local\OpenLiveWriter
2016-01-06 21:50:36> Program: Install path C:\Users\jason\AppData\Local\OpenLiveWriter already exists, burning it to the ground
2016-01-06 21:50:36> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Auth.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
2016-01-06 21:50:36> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Auth.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\jason\AppData\Local\OpenLiveWriter\app-0.5.1.4\Google.Apis.Auth.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.M
[OLW SquirrelSetup.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/79579/OLW.SquirrelSetup.txt)
oveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

ENDS

If anyone needs screen video, etc, or anything else, to reproduce the fault, please do let me know.

jason
founder
ja2025

. . .

**Comment by paulcbetts** [comment]
```
2016-01-06 21:50:36> Program: Install path C:\Users\jason\AppData\Local\OpenLiveWriter already exists, burning it to the ground
2016-01-06 21:50:36> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 
```

**Comment by willduff** [comment]
Please make sure to close the app before installing. Let us know if you are still unable to install. Thanks!
