### ISSUE TITLE
Posting a draft to Google Blogger and then attempting to publish it sometimes throws a Google.Apis.Requests.RequestError 404

### ISSUE THREAD

**Issue by cgroveacademy** [OpenLiveWriter/OpenLiveWriter#298]
I posted a draft to my blog today, then I went back in to edit it in OLW and went to schedule it...  I got this The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

I deleted it from blogger (the draft) and tried to schedule the post again, same thing.  Any ideas?

**Comment by rdelbar** [comment]
Same problem here, when trying to publish from OLW to Blogger (fujixtras.blogspot.com)

**Comment by pmbweaver** [comment]
I had this issue for several days and couldn't figure out what was going on. I unistalled OLW and reinstalled it, and it worked great. It is worth a try.

**Comment by willduff** [comment]
I've hit this bug myself too. It has something to do with posting a draft. We should look into this and fix it.

**Comment by pmbweaver** [comment]
I uninstalled OLW and reinstalled it and it worked great. Try that.



On Friday, January 15, 2016, Will Duff <notifications@github.com> wrote:

> I've hit this bug myself too. It has something to do with posting a draft.
> We should look into this and fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/298#issuecomment-172086567>
> .
>


-- 
http://wheresweaver.blogspot.com

**Comment by willduff** [comment]
I've got a fix for this out as pull request #367.

**Comment by willduff** [comment]
My fix is checked in and will be included in the next official OLW release.

**Comment by sboyd000** [comment]
Can't post directly from Live writer or to draft on google blogger.  Using latest Live Writer version and windows 7.  This is the message I get.  I've researched it all day to no avail.   Can someone tell me what's up and help?

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ewinger1** [comment]
What does this mean?

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment]
We're fairly certain it means the authentication has lapsed. Can you try re-adding your blog to Live Writer (including re-authenticating with Google) and see if that then lets you post.

**Comment by ewinger1** [comment]
How do you "re-add"?

**Comment by ScottIsAFool** [comment]
If you go File > Options > Accounts then click on Add and just go through the process of adding your blog again. Once you've done that, you can remove the previous instance of it.

**Comment by ewinger1** [comment]
Got it!  It worked!! Thank you!!!!

**Comment by drtufte** [comment]
I don't think that's it. I was just using OLW to post to Blogger. Published 2 saved drafts. No problem. Attempted to publish a third saved post. Got this error. Wrote a brand new one, and it published just fine. Went back to the denied draft, and attempted to publish, and the error came back. Wrote two more  test posts, saved one, published the unsaved one successfully, then published the saved one successfully. Went back to my problem post, tried again, and got the same error.

Did no authentication changes at all in this time.
