### ISSUE TITLE
Unexpected Error - GoogleApiException

### ISSUE THREAD

**Issue by WizDesu** [OpenLiveWriter/OpenLiveWriter#349]
I have this bug

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
We're sorry, but the value for field labels was not valid. [400]
Errors [
	Message[We're sorry, but the value for field labels was not valid.] Location[ - ] Reason[invalid] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

![screenshot_1](https://cloud.githubusercontent.com/assets/17015798/12735391/46fdc542-c926-11e5-8ca2-bb3a5b145cc4.jpg)

**Comment by ScottIsAFool** [comment]
Had you included a number of labels for the blog post?

**Comment by Shoshiplatypus** [comment]
I have just started getting this problem, too. I have been careful to keep the labels to a maximum of 20 which I believe is all we are allowed. However many labels I add, I still get this error message. Can anyone help, please? Why has this suddenly started happening?

Shoshi

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
