### ISSUE TITLE
Support SSL/TLS SNI (Server name indication)

### ISSUE THREAD

**Issue by SAprelov** [OpenLiveWriter/OpenLiveWriter#352]
I have custom blog service with AtomPub protocol support. Host IIS server require SNI (local shared host) When I try to connect to the server I'm getting:

OpenLiveWriter,2.32964,None,00072,03-Feb-2016 17:04:16.012,"System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at OpenLiveWriter.BlogClient.BlogClientBase.CreateAuthenticatedCredential()
   at OpenLiveWriter.BlogClient.BlogClientBase.Login()
   at OpenLiveWriter.BlogClient.Clients.AtomClient.GetUsersBlogs()
   at OpenLiveWriter.BlogClient.Detection.BlogAccountDetector.ValidateService()",""
OpenLiveWriter,2.32964,None,00073,03-Feb-2016 17:04:16.012,"== END WebException =======================",""

Is it OLW || .net || my server?
Thanks.

**Comment by dorianmuthig** [comment]
Looks like your server is closing the connection, before the TLS handshake can complete. Try enabling Keep-Alive requests.

**Comment by SAprelov** [comment]
Well. The reason was unsupported TLS protocol version. The only 1.2 version was on server. OWL needs 1 or 1.1.
Solved)

**Comment by dorianmuthig** [comment]
Does OWL really explicitly specify the version to use for connecting? (which is bad practice, but hey) Because otherwise, this is dependent on the settings of your operating system and the TLS cipher suites it supports. On a default Windows installation, before Windows 8/Server 2012, TLS1.2 and 1.1 need to be manually enabled or you need to install one of the Internet Explorer updates which do it for you.
However, if you have configured your server to use only cipher suites Windows' SChannel library doesn't support, OWL won't be able to connect, of course. That last thing however does seem unlikely, since you're using IIS, which only runs on Windows, unless you have a reverse proxy in between.

**Comment by SAprelov** [comment]
I beleave it not OWL but .Net less than 4.6

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
