### ISSUE TITLE
Can't open blogger "page" for editing

### ISSUE THREAD

**Issue by Lozula** [OpenLiveWriter/OpenLiveWriter#378]
On blogger, when I go to open a page from my blog, I can retrieve the pages, but when I try to open one for editing I get the following error:

System.ArgumentException: PostId was not part of the headers fetched
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPost(String postId)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.RetrieveSelectedPost()
   at OpenLiveWriter.PostEditor.OpenPost.OpenPostForm.AcceptSelectedPost()

I guess because it's not a post? It does retrieve the list of pages correctly, which indicates something is working correctly.

Windows 10, OLW 0.6.0.0

**Comment by ibonobo** [comment]
I tried opening a Page (for the first time) and got the error message. Subsequent attempts (2) were all successful, however. Have you tried again?

**Comment by Lozula** [comment]
The first time I did this I tried multiple times and it didn't work. Today I tried and it worked first time. So I'm stumped.

**Comment by hsandt** [comment]
Same error, retried after reading this post and it worked the 2nd time.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
