### ISSUE TITLE
Unexpected Error - GoogleApiException

### ISSUE THREAD

**Issue by WizDesu** [OpenLiveWriter/OpenLiveWriter#397]
I NEED SOLUTION PLS!!

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by kathweaver** [comment]
What exactly are you doing when you get the exception?

**Comment by sboyd000** [comment]
Having similar problem.  Posted yesterday from a saved post and everything was fine.  Today I get this message over and over again.  I've tried redoing my password, recreated my blog.  So far nothing works and I can't find anyone who has had this problem since January.  Using version 0.6 of OWL with Windows 7.   Not one single problem until today and no solutions on line that I can find.

Here's the error:  Sure hope you can help.

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by sboyd000** [comment]
Anybody have any suggestion for a 404 error that I get when posting directly from Live Writer or to Draft in google? Can't post anything anywhere although everything was working fine yesterday and I did nothing but turn the machine off and then back on overnight. Using Live Writer version 0.6 and windows 7. Here's the error I've been getting all day long between my unsuccessful efforts to research a solution on line.

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

at Google.Apis.Requests.ClientServiceRequest`1.Execute()
at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()
 @sboyd000
  
            
 
Write

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
