### ISSUE TITLE
Unable to add Blogger Account

### ISSUE THREAD

**Issue by ns6955** [OpenLiveWriter/OpenLiveWriter#434]
I just installed OLW on a new laptop Win 8.1 but I get an error when adding my Blogger Account.

Unexpected Error Occurred
An unexpected error has occurred within the application.

System.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetRequestStream(System.Object, System.String)'.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenLiveWriter.PostEditor.Configuration.Wizard.WeblogConfigurationWizardPanelGoogleBloggerAuthentication.<buttonLogin_Click>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

**Comment by Happy4OLW** [comment]
Just curious, were you ever able to resolve this.  I am having the same issue. Thanks.

**Comment by ns6955** [comment]
Yes it did, and of its own, if I remember correctly.

On 25-07-16 06:58 AM, Happy4OLW wrote:

Just curious, were you ever able to resolve this. I am having the same issue. Thanks.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
