### ISSUE TITLE
Problems with Open Writer

### ISSUE THREAD

**Issue by farsideoffifty** [OpenLiveWriter/OpenLiveWriter#440]
I just tried to post to my blog and have gotten this message several times. here is the link to my blog.  I always use delayed postings. http://farsideoffifty.blogspot.com/

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Backend Error [500]
Errors [
	Message[Backend Error] Location[ - ] Reason[backendError] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by farsideoffifty** [comment]
It has been resolved.  Thank you

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
