### ISSUE TITLE
Unable to run/reinstall OpenLiveWriter version 0.6.0.0

### ISSUE THREAD

**Issue by mswcap** [OpenLiveWriter/OpenLiveWriter#456]
OLW doesn't work anymore. When I try to open it, it shows this error: 'Unexpected Error'. So I removed it, downloaded the most recent version (0.6.0.0) but still the same error is thrown. I run Windows 10 Enterprise. Strangest thing is that it worked before without any glitches. But now it doesn't work anymore. Please advise.

Error details:
donderdag 28 april 2016 08:40:38

Version: 0.6.0.0

OS Version: Microsoft Windows NT 6.2.9200.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\mwf\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 95%
Total Physical: 16272 MB
Available Physical: 665 MB
Total Page File: 20880 MB
Available Page File: 3323 MB
Total Virtual: 2047 MB
Available Virtual: 1707 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.

System.IO.FileNotFoundException: Creating an instance of the COM component with CLSID {7AB36653-1796-484B-BDFA-E74F1DB7C1DC} from the IClassFactory failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at PlatformSpellCheck.SpellChecker.IsLanguageSupported(String languageTag)
   at OpenLiveWriter.SpellChecker.WinSpellingChecker.IsLanguageSupported(String bcp47Code)
   at OpenLiveWriter.SpellChecker.SpellingSettings.get_Language()
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.ApplySpellingSettings(Object sender, EventArgs args)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor..ctor(IMainFrameWindow mainFrameWindow, Panel panelEditorContainer, IBlogPostEditingSite postEditingSite)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.Create(IMainFrameWindow mainFrameWindow, Control editorContainer, IBlogPostEditingSite postEditingSite)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.InitializeHtmlEditor()
   at OpenLiveWriter.PostEditor.PostEditorMainControl.InitializeUI()
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace()
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e)

**Comment by mswcap** [comment]
Okay. I located the issue:

Since I run Windows 10 and use the default Mail program to handle my outlook account (xyz@outlook.com), it uses the default spell checker. But it doesn't work as intended since it doesn't accept my Dutch input since Windows 10 is set to English. 

In order to solve this spell checker issue, I found a workaround: To rename the related DLL file _(C:\Windows\System32\MsSpellCheckingFacility.dll)_ to_ MsSpellCheckingFacility.dll.old_.

However the OLW installer AND program itself check for the availability of that DLL. When not found, it throws this error and stops the program from running.

For now I've renamed the DLL file to the old name and now OLW works as intended.
![owl and spell check dll](https://cloud.githubusercontent.com/assets/16236919/14877624/abae7e64-0d1e-11e6-900f-4ea9b94b9540.jpg)

**Comment by ScottIsAFool** [comment]
So to confirm: Live Writer is looking for the MsSpellCheckingFacility.dll?

**Comment by mswcap** [comment]
Looks like it, yes.

**Comment by ScottIsAFool** [comment]
@mswcap ok, thanks.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
