### ISSUE TITLE
(400) Error when inputing a new label

### ISSUE THREAD

**Issue by Indy27** [OpenLiveWriter/OpenLiveWriter#469]
Want to put a new category and hit publish, get this message (this is on latest version btw):

> The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError

> We're sorry, but the value for field labels was not valid. [400]
> Errors [
> 	Message[We're sorry, but the value for field labels was not valid.] Location[ - ] Reason[invalid] Domain[global]
> ]
> 
>    at Google.Apis.Requests.ClientServiceRequest`1.Execute()
>    at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
>    at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
>    at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
>    at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

But somehow the new tag works if I put it in blogger, open up OLW, and use said tag on other posts to publish. WTF?

**Comment by Indy27** [comment]
I wish we had a definite answer for this.

**Comment by Indy27** [comment]
So, am I like the ONLY person to have this problem or not, because I tried 5.1.3, 5.1.4, and the latest version of OLW and it still has this same problem. For me, it's making OLW useless for the time being.

**Comment by ScottIsAFool** [comment]
Weird, I just tried it and it's working fine for me. Just tried it with this:
![image](https://cloud.githubusercontent.com/assets/1658896/15743185/92b14942-28bb-11e6-9ee5-9ff849e00ad5.png)
How many categories are you adding?

**Comment by banders03** [comment]
I'm not a developer, just a user, but I can feel your frustration and 
wish I could help. I haven't added a new label for a while so I don't 
know if I have that problem or not, but otherwise OLW is working 
flawlessly for me. I'm sure you've done all the usual: reboot, 
uninstall/reinstall OLW, etc.

On 6/2/2016 7:02 AM, Indy27 wrote:
>
> So, am I like the ONLY person to have this problem or not, because I 
> tried 5.1.3, 5.1.4, and the latest version of OLW and it still has 
> this same problem. For me, it's making OLW useless for the time being.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/469#issuecomment-223260458>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/APkdI-ScpuHGRK9CT27BiDLLH9zkWz9gks5qHrg0gaJpZM4Iq7ae>.
>

-- 
*Barbara*
My Blog: Paper Pursuits <http://barspaperpursuits.blogspot.com>
My Instagram Feed <https://instagram.com/banders03123/>
Proudly Designing for: My Favorite Things Stamps 
<http://www.mftstamps.com/index.php?route=common/home%27>, Color 
Throwdown Challenge <http://colorthrowdown.blogspot.com/%27>, and Crazy 
4 Challenges <http://crazy4challenges.blogspot.com/%27>.

"If you're not part of the future, get out of the way." John Mellencamp

**Comment by Indy27** [comment]
@shanselman it'll publish/draft save post for existing categories just fine but once I add a new label in a recent or new post that error pops up, and all this has happened for two weeks now. I was using 0.6 at the time, went back to 5.1.4 but to no avail.

@banders03 Tried all that and still come up with this error. I also had this problem where anytime I re-install a fresh OLW, the installation will fail to load the setup and some log appears.  Now I don't know if it's an OLW issue or a Google issue, and it seems I'm the only one affected by this, but I'm about to panic.

**Comment by Indy27** [comment]
one with error, new category: 
!http://funkyimg.com/i/2cv7P.png

one with category used months ago:
!http://funkyimg.com/i/2cv7Q.png

**Comment by Indy27** [comment]
I'm thinking whatever file is for categories somewhere in the directory is corrupted.

**Comment by Indy27** [comment]
Maybe it'll be best if I get a fresh set of files needed that works with categories because this is ridiculous, even System Restore didn't do much help.

**Comment by Indy27** [comment]
Screenshots added to topic.

**Comment by ScottIsAFool** [comment]
Are you able to give us the address of your blog?

**Comment by Indy27** [comment]
I would...it's NSFW though.

**Comment by ScottIsAFool** [comment]
If you would prefer to email it, that's fine, my email address is on my profile.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
