### ISSUE TITLE
Fix PostEditorStorageException in OpenLiveWriter.PostEditor.PostEditorFile.SaveCore

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter#475]
### Stacktrace (first of multiple) ###

<pre>OpenLiveWriter.PostEditor.PostEditorFile;SaveCore;;
OpenLiveWriter.PostEditor.PostEditorFile;SaveBlogPost;;
OpenLiveWriter.PostEditor.BlogPostEditingManager;PrePublishHooks;;
OpenLiveWriter.PostEditor.UpdateWeblogProgressForm;OnShown;;
System.Windows.Forms.Form;CallShownEvent;;
System.Windows.Forms.Control;InvokeMarshaledCallbackDo;;
System.Windows.Forms.Control;InvokeMarshaledCallbackHelper;;
System.Threading.ExecutionContext;RunInternal;;
System.Threading.ExecutionContext;Run;;
System.Threading.ExecutionContext;Run;;
System.Windows.Forms.Control;InvokeMarshaledCallback;;
System.Windows.Forms.Control;InvokeMarshaledCallbacks;;</pre>

### Reason ###

OpenLiveWriter.PostEditor.PostEditorStorageException: Error Accessing Local Post - Unexpected error occurred while accessing local post (-2147287008)

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/249213/crash_reasons/112565227](https://rink.hockeyapp.net/manage/apps/249213/crash_reasons/112565227)

**Comment by rfulwell** [comment]
I am unable to access the crash data on hockeyapp.net after setting up an account there. Do I need an invitation to see the dump, etc.?

**Comment by ScottIsAFool** [comment]
Package: openlivewriter
Version: 0.6.0.0
OS: Microsoft Windows NT 6.2.9200.0
Date: 2016-02-26T18:52:47

OpenLiveWriter.PostEditor.PostEditorStorageException: Error Accessing Local Post - Unexpected error occurred while accessing local post (-2147287008)

Share violation--storage may already be opened.
   at OpenLiveWriter.PostEditor.PostEditorFile.SaveCore(IBlogPostEditingContext editingContext, PostEditorFile autoSaveSourceFile, String filePath)
   at OpenLiveWriter.PostEditor.PostEditorFile.SaveBlogPost(IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.PrePublishHooks(Object sender, PublishEventArgs args)
   at OpenLiveWriter.PostEditor.UpdateWeblogProgressForm.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by rfulwell** [comment]
My cursory inspection shows a storage open exception probably thrown due to another lock on the file. It seems likely that some code (somewhere) is not properly disposing of resources.

It looks like someone has taken a crack at debugging this problem before: 
\src\managed\OpenLiveWriter.Interop\Com\StructuredStorage\Storage.cs@396

```C#
#if FALSE
        /// <summary>
        /// Storage finalizer
        /// </summary>
        ~Storage()
        {
            //Debug.Assert(storage == null, "Object not disposed properly - Use Close or Dispose!");
        }
#endif
```

Before I go hunting for missing using blocks, this bug is marked "high-priority." @martinwoodward how does this bug manifest? Are there any reliable repro steps?

**Comment by ScottIsAFool** [comment]
@rfulwell Just FYI, @martinwoodward is down as raising this, but it has come directly from HockeyApp and isn't something Martin has repro'd himself.

**Comment by dougrathbone** [comment]
This is the same root cause as #678, which was fixed in #1050. Closing as duplicate.
