### ISSUE TITLE
Username/Password Error - Error message included

### ISSUE THREAD

**Issue by Happy4OLW** [OpenLiveWriter/OpenLiveWriter#482]
I upgraded to Windows 8.1 (bad move) in preparation to upgrading to Windows 10 (won't be doing that now!) and I am having trouble getting the open live writer to work.  I have the nightly edition.  It wasn't recognizing my username and password so I deleted the blog (as someone in another thread suggested) and tried to add it back but now I'm getting the following message when trying to sign in to add my blog:

System.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetRequestStream(System.Object, System.String)'.
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

Can anyone help me?

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
