### ISSUE TITLE
OpenLiveWriter.exe doesn't exist in current release

### ISSUE THREAD

**Issue by kalobyte** [OpenLiveWriter/OpenLiveWriter#500]
I have just downloaded the installer and after installation and starting update.exe I see in SquirrelSetup.log.
There is nothing appears on the screen.  OpenLiveWriter.exe doesn't exists.
I use win 8.1 en + ,net 4.5 + msvs 2013

2016-08-26 16:39:15> Program: Starting Squirrel Updater: 
2016-08-26 16:40:03> Program: Starting Squirrel Updater: --processStart OpenLiveWriter.exe
2016-08-26 16:40:03> Program: Want to launch 'C:\Users\admin\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe'
2016-08-26 16:40:03> Program: File C:\Users\admin\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe doesn't exist in current release
2016-08-26 16:40:03> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

**Comment by rkingett** [comment]
same thing for me and I am on windows 10

**Comment by ScottIsAFool** [comment]
I think you need to make sure you have .net 4.6 installed.

**Comment by kalobyte** [comment]
I have 4.6 installed, but it was already installed.
Update.exe starts to collect some data about new blog and crashes.
Open Live Writer.log
OpenLiveWriter,1.1496,None,00001,26-Aug-2016 19:37:47.400,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,1.1496,None,00002,26-Aug-2016 19:37:47.400,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.1496,None,00003,26-Aug-2016 19:37:47.435,"Failed to load blog settings for: ",""
OpenLiveWriter,1.1496,None,00004,26-Aug-2016 19:37:47.435,"Default blog has invalid client type, ignoring blog.",""

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
