### ISSUE TITLE
Writer does not work.

### ISSUE THREAD

**Issue by Boatwoman** [OpenLiveWriter/OpenLiveWriter#502]
Please can someone help me. I have been using Windows Live Writer for a long time and now it has changed, I cannot get it to load. 
It comes up with this message:

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
    at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
    --- End of inner exception stack trace ---
    at Google.Apis.Requests.ClientServiceRequest`1.Execute()
    at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
    at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
    at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
    at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

Can anyone help me with a solution please.

**Comment by lextm** [comment]
"Could not create SSL/TLS secure channel" means a HTTPS connection cannot be set up. To know the exact cause you have to analyze why it fails via a tool such as Wireshark. There are examples over the internet [like this](http://www.technologydwell.com/2012/05/securesockets-layer-ssl-is-internet.html) showing how to get started.

Due to the recent security events on SSL/TLS, it is quite possible that Google Bloggers now require a stricter HTTPS connection, which your machine could not support. So careful analysis is mandate before the solution can be found.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
