### ISSUE TITLE
Unable to Open (Windows Store Version)

### ISSUE THREAD

**Issue by jaliyaudagedara** [OpenLiveWriter/OpenLiveWriter#517]
Hi,

Upon opening up the OpenLiveWriter (Windows Store Version), I am getting the following error.

```
Wednesday, September 28, 2016 8:14:16 AM

Version: 0.6.1.0

OS Version: Microsoft Windows NT 10.0.14393.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Program Files\WindowsApps\D5BA6BCD.OpenLiveWriter_0.6.1.0_x86__7g8mfyn71hpbp\VFS\Users\ContainerAdministrator\AppData\Local\OpenLiveWriter\app-0.6.1.0\OpenLiveWriter.exe" 

Memory Load: 19%
Total Physical: 65402 MB
Available Physical: 52907 MB
Total Page File: 75130 MB
Available Page File: 60208 MB
Total Virtual: 2047 MB
Available Virtual: 1631 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.PostHtmlEditingSettings.GetEditorTemplateHtml(BlogEditingTemplateType templateType, Boolean forceRTL)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.EditingTemplateLoader.LoadBlogTemplate(String blogId, BlogEditingTemplateType templateType, Boolean forceRTL)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.GetStyledHtml()
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.Initialize(IBlogPostEditingContext editingContext, IBlogClientOptions clientOptions)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OnBlogPostChanged()
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.EditPost(IBlogPostEditingContext editingContext, Boolean forceDirty)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace()
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e)
```
Illegal characters in path, how to get that resolved?

Thanks.
Jaliya

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.

**Comment by jaliyaudagedara** [comment]
@shanselman, of course Scott, completely understood. thanks for the comment
