### ISSUE TITLE
Server Error 500 when posting to Blogger

### ISSUE THREAD

**Issue by Lozula** [OpenLiveWriter/OpenLiveWriter#524]
When publishing my blog posts to Blogger, I am constantly receiving error 500 server codes (see image below), which I believe are coming back from google photos as part of the upload to the OpenLiveWriter Google Photos album. Usually one or two images will upload, then I'll get an error 500, and have to hit publish again, and then it will upload a couple more, and the process will stop again. I suspect something is awry with the google photos api since Picasa shut down, which is causing uploads from third party tools to error out. 

![image](https://cloud.githubusercontent.com/assets/16286517/19420141/4c222ff4-93dd-11e6-9b9f-aa120ee5bdb7.png)

And the error in the OLW log file is:

OpenLiveWriter,1.5192,Fail,00297,16-Oct-2016 20:15:21.880,"System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenLiveWriter.BlogClient.Clients.RedirectHelper.GetResponse(String initialUri, RequestFactory requestFactory)
   at OpenLiveWriter.BlogClient.Clients.XmlRestRequestHelper.SimpleRequest(String method, Uri& uri, HttpRequestFilter filter, WebHeaderCollection& responseHeaders, String[] parameters)
   at OpenLiveWriter.BlogClient.Clients.XmlRestRequestHelper.Get(Uri& uri, HttpRequestFilter filter, WebHeaderCollection& responseHeaders, String[] parameters)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetBlogImagesAlbum(String albumName)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.PostNewImage(String albumName, String filename, String& srcUrl, String& editUri)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.DoBeforePublishUploadWork(IFileUploadContext uploadContext)
   at OpenLiveWriter.PostEditor.WeblogBlogFileUploader.DoUploadWorkBeforePublish(IFileUploadContext uploadContext)","   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at OpenLiveWriter.CoreServices.Diagnostics.LogFileTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at OpenLiveWriter.PostEditor.WeblogBlogFileUploader.DoUploadWorkBeforePublish(IFileUploadContext uploadContext)
   at OpenLiveWriter.PostEditor.BlogPostReferenceFixer.FileUploadWorker.DoUploadWork(String fileReference, BlogFileUploader fileUploader, Boolean isLightboxCloneEnabled)
   at OpenLiveWriter.PostEditor.BlogPostReferenceFixer.LocalFileTransformer.Transform(BeginTag tag, String reference)
   at OpenLiveWriter.CoreServices.HTML.HtmlReferenceFixer.LocalFileReferenceFixupFilter.FixReferences(BeginTag tag, String reference)
   at OpenLiveWriter.CoreServices.HTML.HtmlReferenceFixer.OnBeginTag(BeginTag tag)
   at OpenLiveWriter.CoreServices.LightWeightHTMLDocumentIterator.Parse()
   at OpenLiveWriter.CoreServices.HTML.HtmlReferenceFixer.FixReferences(String html, ReferenceFixer fixer, ReferenceFixedCallback referenceFixed)
   at OpenLiveWriter.CoreServices.HTML.HtmlReferenceFixer.FixLocalFileReferences(String html, ReferenceFixer fixer, ReferenceFixedCallback referenceFixed)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.LocalSupportingFileUploader.UploadFilesBeforePublish()
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()"

I published a help request on the Google Blogger and Google Photos forums to no avail - any ideas?

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
