### ISSUE TITLE
Can't Connect to DigitalOcean Wordpress host

### ISSUE THREAD

**Issue by nigelainscoe** [OpenLiveWriter/OpenLiveWriter#525]
When trying to set up the to connect to a Wordpress install on a Ubuntu 16.04.2 server running PHP 7 I get the following error.

![image](https://cloud.githubusercontent.com/assets/822636/19452203/0f10c35c-94a8-11e6-9c26-21754a71dc02.png)

The Apache error log shows the following error:
[Mon Oct 17 19:20:36.724994 2016] [:error] [pid 11983] [client XXX.18.179.230:4497] PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /var/www/html/wp-includes/class-IXR.php:264\nStack trace:\n#0 /var/www/html/wp-includes/class-IXR.php(464): IXR_Message->parse()\n#1 /var/www/html/wp-includes/class-IXR.php(432): IXR_Server->serve('<?xml version="...')\n#2 /var/www/html/wp-includes/class-IXR.php(440): IXR_Server->__construct(Array, false, false)\n#3 /var/www/html/wp-includes/class-wp-xmlrpc-server.php(197): IXR_Server->IXR_Server(Array)\n#4 /var/www/html/xmlrpc.php(84): wp_xmlrpc_server->serve_request()\n#5 {main}\n  thrown in /var/www/html/wp-includes/class-IXR.php on line 264

Any suggestions greatly appreciated. My PHP is a bit ropey

**Comment by nigelainscoe** [comment]
Fixed it. PHP XML Missing.
