### ISSUE TITLE
Google.Apis.Requests.RequestError Not Found [404]

### ISSUE THREAD

**Issue by sboyd000** [OpenLiveWriter/OpenLiveWriter#526]
Apparently this was an issue 10 or 11 months ago but I just started having it today - October 18, 2016 - after having no problems with Live Writer for months and months.  Can't figure out what to do.  I tried to upgrade to the latest version but am not sure it worked.  I got no subwindows.  Do I have to delete the current version before installing the latest?  Where can I find the version currently in use so I can know if the upgrade worked?  I have rebooted my machine just in case.   Using Windows 7 (I know, I know) but it's been working perfectly until today.   Can I get some help here?  After a couple of hours of this I don't know where to go.

**Comment by sboyd000** [comment]
DUH - found the version it is build 0.6

**Comment by sboyd000** [comment]
I can  post something very short with no pictures.  Does this have something to do with pictures?

**Comment by MamaTierney** [comment]
I am having same issues.  Saved draft without photos and was fine, but as soon as photos were added I get this message:

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
