### ISSUE TITLE
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)

### ISSUE THREAD

**Issue by kunal-chowdhury** [OpenLiveWriter/OpenLiveWriter#534]
### Getting the following exception on 'Open Live Writer build 0.6.0.0':
System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))

**Here's the complete log:**

> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at OpenLiveWriter.Mshtml.IHTMLPaintSiteInvalidateAll.InvalidateRect(IntPtr prcInvalid)
   at OpenLiveWriter.Mshtml.MshtmlElementBehavior.Invalidate()
   at OpenLiveWriter.PostEditor.PostHtmlEditing.PostBodyEditingElementBehavior.OnSelectedChanged()
   at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior.UpdateSelectionState()
   at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior._editorContext_SelectionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OnSelectionChanged(EventArgs e, IHtmlEditorSelection newSelection, Boolean moveSelectionToFont)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OpenLiveWriter.HtmlEditor.IHtmlEditorComponentContext.set_Selection(IHtmlEditorSelection value)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.ResetSelection()
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl._mshtmlEditor_DocumentComplete(Object sender, EventArgs e)
   at OpenLiveWriter.Mshtml.MshtmlEditor.OnDocumentComplete()
   at OpenLiveWriter.Mshtml.MshtmlEditor.ReadyStateChangedHandler(Object sender, EventArgs ea)

**Comment by kunal-chowdhury** [comment]
Any update on the said issue? I am still getting the following error when 'Open Live Writer' is in idle mode for few minutes:

> 
> Wednesday, 8 March, 2017 10:37:31 AM
> Version: 0.6.0.0
> 
> OS Version: Microsoft Windows NT 6.2.9200.0
> Runtime version: 4.0.30319.42000
> Shutdown started: False
> Program: "C:\Users\kunal\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe" 
> 
> Memory Load: 41%
> Total Physical: 8082 MB
> Available Physical: 4717 MB
> Total Page File: 10002 MB
> Available Page File: 6496 MB
> Total Virtual: 2047 MB
> Available Virtual: 1425 MB
> Available Extented Virtual: 0 MB
> 
> Unexpected Error Occurred
> An unexpected error has occurred within the application.
> 
> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
>    at OpenLiveWriter.Mshtml.IHTMLPaintSiteInvalidateAll.InvalidateRect(IntPtr prcInvalid)
>    at OpenLiveWriter.Mshtml.MshtmlElementBehavior.Invalidate()
>    at OpenLiveWriter.PostEditor.PostHtmlEditing.PostBodyEditingElementBehavior.OnSelectedChanged()
>    at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior.UpdateSelectionState()
>    at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior._editorContext_SelectionChanged(Object sender, EventArgs e)
>    at System.EventHandler.Invoke(Object sender, EventArgs e)
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OnSelectionChanged(EventArgs e, IHtmlEditorSelection newSelection, Boolean moveSelectionToFont)
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OpenLiveWriter.HtmlEditor.IHtmlEditorComponentContext.set_Selection(IHtmlEditorSelection value)
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl.ResetSelection()
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl._mshtmlEditor_DocumentComplete(Object sender, EventArgs e)
>    at OpenLiveWriter.Mshtml.MshtmlEditor.OnDocumentComplete()
>    at OpenLiveWriter.Mshtml.MshtmlEditor.ReadyStateChangedHandler(Object sender, EventArgs ea)

**Comment by Laronski** [comment]
Have you updated to the latest version?
0.6.1.0?

https://goo.gl/Wa8WGC

**Comment by kunal-chowdhury** [comment]
Thanks @Laronski. I have upgraded. It is working fine.

**Comment by kunal-chowdhury** [comment]
Still getting the same error on 0.6.1.0 :(

**Comment by kunal-chowdhury** [comment]
Could anyone working on this please check this error? I am continuously getting it after every 5-10 mints interval. Once again the log:


> Thursday, 20 April, 2017 09:25:29 PM
> 
> Version: 0.6.1.0
> 
> OS Version: Microsoft Windows NT 10.0.15063.0
> Runtime version: 4.0.30319.42000
> Shutdown started: False
> Program: "C:\Program Files\WindowsApps\D5BA6BCD.OpenLiveWriter_0.6.1.0_x86__7g8mfyn71hpbp\VFS\Users\ContainerAdministrator\AppData\Local\OpenLiveWriter\app-0.6.1.0\OpenLiveWriter.exe" 
> 
> Memory Load: 47%
> Total Physical: 8082 MB
> Available Physical: 4280 MB
> Total Page File: 14226 MB
> Available Page File: 10047 MB
> Total Virtual: 2047 MB
> Available Virtual: 1418 MB
> Available Extented Virtual: 0 MB
> 
> Unexpected Error Occurred
> An unexpected error has occurred within the application.
> 
> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
>    at OpenLiveWriter.Mshtml.IHTMLPaintSiteInvalidateAll.InvalidateRect(IntPtr prcInvalid)
>    at OpenLiveWriter.Mshtml.MshtmlElementBehavior.Invalidate()
>    at OpenLiveWriter.PostEditor.PostHtmlEditing.PostBodyEditingElementBehavior.OnSelectedChanged()
>    at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior.UpdateSelectionState()
>    at OpenLiveWriter.HtmlEditor.HtmlEditorElementBehavior._editorContext_SelectionChanged(Object sender, EventArgs e)
>    at System.EventHandler.Invoke(Object sender, EventArgs e)
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OnSelectionChanged(EventArgs e, IHtmlEditorSelection newSelection, Boolean moveSelectionToFont)
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OpenLiveWriter.HtmlEditor.IHtmlEditorComponentContext.set_Selection(IHtmlEditorSelection value)
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl.ResetSelection()
>    at OpenLiveWriter.HtmlEditor.HtmlEditorControl._mshtmlEditor_DocumentComplete(Object sender, EventArgs e)
>    at OpenLiveWriter.Mshtml.MshtmlEditor.OnDocumentComplete()
>    at OpenLiveWriter.Mshtml.MshtmlEditor.ReadyStateChangedHandler(Object sender, EventArgs ea)
>

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
