### ISSUE TITLE
Blogger account no longer working

### ISSUE THREAD

**Issue by vexillia** [OpenLiveWriter/OpenLiveWriter#536]
I had two working blogger accounts with blogs in OLW.  Now only one account works.  When I try to add a new blog/account or update one of the broken blogs  I can't login to blogger.  It was working two days ago!

Here's the error message:

12 November 2016 11:58:23
Version: 0.6.0.0
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\Business\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe" 

Memory Load: 70%
Total Physical: 2047 MB
Available Physical: 595 MB
Total Page File: 4095 MB
Available Page File: 2552 MB
Total Virtual: 2047 MB
Available Virtual: 1667 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application

System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenLiveWriter.PostEditor.Configuration.Wizard.WeblogConfigurationWizardPanelGoogleBloggerAuthentication.<buttonLogin_Click>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by vexillia** [comment]
Additional error message:

Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_grant", Description:"", Uri:""
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ListRecentPosts(String blogId, Int32 maxPosts, Nullable`1 now, StatusEnum status, PostList previousPage)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by vexillia** [comment]
More digging results after reloading a backup:

[1] Second error message occurs when I tried to get a recent message from one blog.
[2] The Bloggerv3 tokens were there before I requested the recent messages.
[3] After this all Bloggerv3 tokens were gone apart from one which is for the account that stills works.

The Google account that doesn't work does not have OpenLiveWriter as an allowed application (unlike the one that does work).  So it would be great if I could just re-request permission.  This doesn't work (see first error message posted).

Hope this helps someone spot what I have to do to get my OpenLiveWriter to work with my second Google account and the three blogs I run from it.

**Comment by vexillia** [comment]
Tried to authorise OLW by creating new user and installing OLW anew.  No luck: same result as above.

**Comment by vexillia** [comment]
OK last attempt.  Did a complete uninstall including registry keys and then re-installed.  Still couldn't contact Blogger.  I give up.

**Comment by lextm** [comment]
You will have to build from source and do further debugging by attaching a debugger (such as Visual Studio) to go through related files, and also use Google's documentation as guide, https://developers.google.com/identity/protocols/OAuth2WebServer?hl=en 

I know you have done a lot above, but without diving into the code it would be difficult to tell what's up.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
