### ISSUE TITLE
Can't reinstall or open the program at all.

### ISSUE THREAD

**Issue by raxster** [OpenLiveWriter/OpenLiveWriter#538]
This is the error that I'm getting.

> Friday, November 25, 2016 1:52:27 AM

Version: 0.6.0.0

OS Version: Microsoft Windows NT 6.2.9200.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\Rams\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 81%
Total Physical: 1974 MB
Available Physical: 370 MB
Total Page File: 3958 MB
Available Page File: 1878 MB
Total Virtual: 2047 MB
Available Virtual: 1662 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.

System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenLiveWriter.PostEditor.PostEditorMainControl.htmlEditor_TitleFocusChanged(Object sender, EventArgs e)
   at OpenLiveWriter.PostEditor.ContentEditor._currentEditor_EditableRegionFocusChanged(Object sender, EventArgs e)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditorControl.OnEditableRegionFocusChanged(EventArgs e)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditorControl.OnDocumentComplete(EventArgs e)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl._mshtmlEditor_DocumentComplete(Object sender, EventArgs e)
   at OpenLiveWriter.Mshtml.MshtmlEditor.OnDocumentComplete()
   at OpenLiveWriter.Mshtml.MshtmlEditor.ReadyStateChangedHandler(Object sender, EventArgs ea)

> 

I've  restarted my laptop several times and uninstalled the program and when I tried to reinstall the program gives the same error.

**Comment by raxster** [comment]
I've also notived that windows live essentials 2012 programs don't also open. 

I've tried the windows store Open Live Writer it also has the same error. 

I'm not sure when this happened because I was able to use the program about 3rd week of October.

**Comment by raxster** [comment]
Never mind. Only solution I could think of was a clean install of windows 10 which did the trick. 

more power to the devs for a great piece of software!

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
