### ISSUE TITLE
Open Live Writer fails to load (Win 7, Google Blogger)

### ISSUE THREAD

**Issue by DebHgn** [OpenLiveWriter/OpenLiveWriter#540]
OLW simply will not load.  (Win 7, Google Blogger.) I've installed, deleted, reinstalled, restarted, tried clean booting and all combinations.  I've deleted the reg keys mentioned to uninstall etc and reinstalled again.  It worked fine a few weeks ago, then I deleted it from the "pin" in my toolbar and it died.  (I mean DEAD!) lol No matter what I do, the program simply will not load, it spins for a second then stops.  In setup it goes thru the entire setup process fine, even posts a temporary post to get the blog theme but then it dies.  Sometimes after I restart the icon is missing as well.  The kicker here is that if I download and install on a different User account it works just fine, but I need it to work on MY user account. 

Currently, if I click the shortcut icon, it beings the install process all over again. Sometimes I get an error when I get to the login to my google account stage.  (Firefox can’t establish a connection to the server at localhost:58418). But if I minimize the browser, there it is ready to load my Google Blogger blog titles. I continue and it detects the blog settings but that's where it ends, the program itself doesn't load. (have I confused you enough yet) lol 

Help! 
Thanks!

**Here is the Log file:**
OpenLiveWriter,1.4388,None,00001,13-Dec-2016 21:16:36.299,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,1.4388,None,00002,13-Dec-2016 21:16:36.299,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.4388,None,00003,13-Dec-2016 21:16:36.713,"Failed to load blog settings for: ",""
OpenLiveWriter,1.4388,None,00004,13-Dec-2016 21:16:36.713,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.4220,None,00001,13-Dec-2016 21:16:44.024,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,1.4220,None,00002,13-Dec-2016 21:16:44.024,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.4220,None,00003,13-Dec-2016 21:16:44.107,"Failed to load blog settings for: ",""
OpenLiveWriter,1.4220,None,00004,13-Dec-2016 21:16:44.107,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.1100,None,00001,13-Dec-2016 21:52:24.494,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,1.1100,None,00002,13-Dec-2016 21:52:24.494,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.1100,None,00003,13-Dec-2016 21:52:24.568,"Failed to load blog settings for: ",""
OpenLiveWriter,1.1100,None,00004,13-Dec-2016 21:52:24.569,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.1100,None,00005,13-Dec-2016 21:53:25.972,"Unable to download file """" during Blog service detection: System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.CreateHttpWebRequest(String requestUri, Boolean allowAutoRedirect, Nullable`1 connectTimeoutMs, Nullable`1 readWriteTimeoutMs)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SendRequest(String requestUri, HttpRequestFilter filter)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SafeSendRequest(String requestUri, HttpRequestFilter filter)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SafeDownloadFile(String fileUrl, String& responseUri, HttpRequestFilter filter)",""
OpenLiveWriter,1.1100,Fail,00006,13-Dec-2016 21:55:40.677,"Exception occurred attempting to download categories for weblog http://blog.dentistthemenace.com/: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SendRequest(String requestUri, HttpRequestFilter filter)
   at OpenLiveWriter.BlogClient.BlogClientHelper.SendAuthenticatedHttpRequest(String requestUri, HttpRequestFilter filter, HttpRequestFilter credentialsFilter)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetCategories(String blogId)
   at OpenLiveWriter.BlogClient.Detection.BlogSettingsDetector.SafeDownloadCategories()","   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at OpenLiveWriter.CoreServices.Diagnostics.LogFileTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at OpenLiveWriter.BlogClient.Detection.BlogSettingsDetector.ReportException(String context, Exception ex)
   at OpenLiveWriter.BlogClient.Detection.BlogSettingsDetector.SafeDownloadCategories()
   at OpenLiveWriter.BlogClient.Detection.BlogSettingsDetector.DetectSettings(IProgressHost progressHost)
   at OpenLiveWriter.PostEditor.Configuration.Wizard.WizardSettingsAutoDetectionOperation.DetectWeblogSettings(IProgressHost progressHost)
   at OpenLiveWriter.CoreServices.Progress.ProgressWorker.DoWork()
   at OpenLiveWriter.CoreServices.Progress.MultipartAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()"
OpenLiveWriter,1.1100,None,00007,13-Dec-2016 21:55:41.231,"Error occurred while downloading weblog style: The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ListRecentPosts(String blogId, Int32 maxPosts, Nullable`1 now, StatusEnum status, PostList previousPage)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Detection.RecentPostRegionLocatorStrategy.PrepareRegions(IProgressHost progress)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplateDetector.GetBlogTemplateFiles(IProgressHost progress, BlogPostRegionLocatorStrategy regionLocatorStrategy, BlogEditingTemplateStrategy[] templateStrategies, BlogEditingTemplateType[] templateTypes)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplateDetector.DetectTemplates(IProgressHost progress, BlogEditingTemplateType[] targetTemplateTypes, BlogEditingTemplateStrategy[] templateStrategies)",""

**Squirrel Log file:**
2016-12-13 21:16:43> Program: Starting Squirrel Updater: --processStart OpenLiveWriter.exe
2016-12-13 21:16:43> Program: Want to launch 'C:\Users\Debbie\AppData\Local\OpenLiveWriter\app-0.6.0\OpenLiveWriter.exe'
2016-12-13 21:16:43> Program: About to launch: 'C:\Users\Debbie\AppData\Local\OpenLiveWriter\app-0.6.0\OpenLiveWriter.exe': 
2016-12-13 21:52:24> Program: Starting Squirrel Updater: --processStart OpenLiveWriter.exe
2016-12-13 21:52:24> Program: Want to launch 'C:\Users\Debbie\AppData\Local\OpenLiveWriter\app-0.6.0\OpenLiveWriter.exe'
2016-12-13 21:52:24> Program: About to launch: 'C:\Users\Debbie\AppData\Local\OpenLiveWriter\app-0.6.0\OpenLiveWriter.exe':

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
