### ISSUE TITLE
Open Live Writer SquirrelSetup.Log Installation Failure  / New Error Messages

### ISSUE THREAD

**Issue by msniw** [OpenLiveWriter/OpenLiveWriter#545]
Hello - I still can't access my old w.posts and  have since received further error messages, one of which did not stay open long enough for me to read it. This is what the legible one said:

ErrorReport1.txt

Wednesday, December 21, 2016 12:25:50 AM

Version: 0.6.0.0

OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Runtime version: 4.0.30319.18444
Shutdown started: False
Program: "C:\Users\TOSHIBA 7\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 88%
Total Physical: 2662 MB
Available Physical: 303 MB
Total Page File: 5323 MB
Available Page File: 1601 MB
Total Virtual: 2047 MB
Available Virtual: 1825 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.

System.IO.FileNotFoundException: Could not load file or assembly 'OpenLiveWriter.BlogClient, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'OpenLiveWriter.BlogClient, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'
   at OpenLiveWriter.ApplicationLauncher.get_BloggingConfigured()
   at OpenLiveWriter.ApplicationLauncher.EnsureBloggingConfigured(IDisposable splashScreen)
   at OpenLiveWriter.ApplicationLauncher.LaunchBloggingForm(String[] args, IDisposable splashScreen, Boolean isFirstInstance)
   at OpenLiveWriter.ApplicationMain.LaunchFirstInstance(IDisposable splashScreen, String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

I really would appreciate some help here, If no-one's able to do anything, I'll try and contact OpenLiveWriter directly. As it is, I've got about five years+ inaccessible work I'm desperate to use.

T/A

Natalie Wood

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
