### ISSUE TITLE
GoogleApiException

### ISSUE THREAD

**Issue by jossie25** [OpenLiveWriter/OpenLiveWriter#563]
I have this problem:

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

Can you help me??

**Comment by Dinchy87** [comment]
Same error here with two of my editors on our website. The same bug. And a 501 exception if they add a picture to the post. So posting is broken totally right now.

**Comment by bayfieldbunch** [comment]
Same here...can only publish text

**Comment by bayfieldbunch** [comment]
here is today's error 2/12:     The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by bayfieldbunch** [comment]
Hopefully someone will respond....

**Comment by bayfieldbunch** [comment]
any fixes yet ?

**Comment by ScottIsAFool** [comment]
I'm trying to find a bit of commonality between the people who are experiencing these errors. I've tried on a couple of blogger blogs that I have with no problems, even when attaching images.
Questions:
1) Does it fail immediately when you add an image? 2
2) If it works with one image but not with multiple, how many before it fails?
3) Do your blogs run on a custom domain? (ie, not a blogger/blogspot domain)

**Comment by SteveP-UK** [comment]
Hi Guys

I'm a regular user of Blogger and I've done a few test posts myself today
and yesterday (with and without pics) - and they all posted fine. Happy to
be a 'second pair of eyes' on this, if you need a third opinion.

Regards

Steve
www.StevePalmer.com
blog.StevePalmer.com
@TweetsBySteveP
Mobile: 07860 639 661
:::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by bayfieldbunch** [comment]
tries to publish ..anywhere from 5 seconds to 1 minute it fails.  we use   thebayfieldbunch.com
Edit


thebayfieldbunch.blogspot.com
redirects

**Comment by ScottIsAFool** [comment]
@Dinchy87 Do all of your site's users have this issue when trying to post?

**Comment by jongalloway** [comment]
Closing as a duplicate of #562
