### ISSUE TITLE
We're sorry, but you don't have permission to access this resource. [403] Errors [

### ISSUE THREAD

**Issue by Rob2540** [OpenLiveWriter/OpenLiveWriter#569]
LW was working fine this morning...went to upload this afternoon and received this message below.
Have tried deleting the program and reinstalling..   same issue. 

does anyone have the solution,  please...

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
We're sorry, but you don't have permission to access this resource. [403]
Errors [
	Message[We're sorry, but you don't have permission to access this resource.] Location[ - ] Reason[forbidden] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment]
Can you please try removing that blog and re-adding it?

**Comment by Rob2540** [comment]
Thank's Scott,  I did that and had some success with some of my blogs,  but others now have me uploading pictures from a google album account I had to set up,  Others allow me to directly cut and paste from my computer.
And now tonight when I saved in drafts and reopen it to further edit, it opens looking like a complete jpeg image, text and photo's are un- editable, can't do a thing to it, other than doing a new post and retyping the whole lot and reinserting photo's,  then I have to upload straight away because drafts doesn't work.......this only happened this afternoon,  this morning was fine...
 very frustraiting as all was working fine a few days ago on all blogs...

**Comment by ScottIsAFool** [comment]
The ones that aren't letting you upload from your computer, are you getting a 501 error? If so, please follow the instructions here http://lehsys.blogspot.com/2017/02/open-live-writer-server-error-501using.html

**Comment by Laronski** [comment]
Curious—
What happens when you turn off the theme?
Can you edit then?

   In Live Writer
    » Blog Account [tab] » Blog Theme button [toggle on/off]

**Comment by Rob2540** [comment]
Yes I can.

**Comment by Rob2540** [comment]
did you come up with a solution...the program is becoming very difficult to work with,  Never been a problem in the past.  what has changed?

**Comment by ScottIsAFool** [comment]
@Rob2540 Did you try what I suggested with that blog post? Assuming you were getting 501 error messages.

**Comment by Rob2540** [comment]
Thanks Scott
I'm not getting the 501 error message.... I uploaded on another blog site this morning without any problems at all.
Each blog seems to be throwing up different problems.

One won't let me cut and paste images, so i have to load from Google Album and in the themeless mode.
One works absolutely fine.
The most important one, the Museum blog, won't let me publish at all.

I have already removed the museum blog and reloaded it without any change and if I try to reopen it from drafts it still opens as  an uneditable solid image with the top spacing thrown out of place
I just tried with the museum blog again and it gave me this message below, with the theme on, and the theme off.  ( it made no difference it wouldn't publish at all)


"The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors ["



Rob Slater
Woollamia Signs and Artwork
598 Woollamia Rd
Woollamia 2540
02 44416383

0439416386

Work site http://www.drift2540.blogspot.com.au/

Local history Blog - http://jervisbaymaritimemuseum.blogspot.com.au/
<http://jervisbaymaritimemuseum.blogspot.com.au>



________________________________

**Comment by Rob2540** [comment]
And something else Scott.
one of my blogs just let me publish a new page without themes without a problem,  then ten minutes later I went to publish a correction
and it threw up the same issue as above...not allowing me to publish at all...

driving me a bit batty here!


Rob Slater
Woollamia Signs and Artwork
598 Woollamia Rd
Woollamia 2540
02 44416383

0439416386

Work site http://www.drift2540.blogspot.com.au/

Local history Blog - http://jervisbaymaritimemuseum.blogspot.com.au/
<http://jervisbaymaritimemuseum.blogspot.com.au>



________________________________

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
