### ISSUE TITLE
Google Api Exception

### ISSUE THREAD

**Issue by 91483** [OpenLiveWriter/OpenLiveWriter#576]
I am not able retrieve posts and pages of my blog from OLW; I uninstalled it and reinstalled it back, still I am getting this below error:  

> The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ListPages(String blogId, Nullable`1 maxPages, StatusEnum status, PageList previousPage)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ListAllPages(String blogId, Nullable`1 maxPages)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetPages(String blogId, Int32 maxPages)
   at OpenLiveWriter.BlogClient.Blog.GetPages(Int32 maxPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPages(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment]
When you reinstalled, did you have to enter your Google credentials again? If you didn't, can you remove that blog account and add it fresh again please.

**Comment by pabalexa** [comment]
The same happened to me and I could solve it. I noticed that the error appeared "Location [-]" then change the settings of my blog and it was solved.

![1](https://cloud.githubusercontent.com/assets/6232759/24597351/b1b922ec-181b-11e7-84cd-26f6e80718b4.jpg)

![2](https://cloud.githubusercontent.com/assets/6232759/24597358/b70e5ffa-181b-11e7-95e8-0df1dd860ea8.jpg)

Also place the feed with full access, but I think this last modification is unnecessary. 

![3](https://cloud.githubusercontent.com/assets/6232759/24597361/bd7fe1b0-181b-11e7-83c3-9f997eeabaaa.jpg)

I do not know what the problem is exactly, but what I did was a solution for me and I wanted to share because I might be able to serve.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
