### ISSUE TITLE
Open Live Writer v6.2.0 - (one off) error publishing to Blogger

### ISSUE THREAD

**Issue by Laronski** [OpenLiveWriter/OpenLiveWriter#591]
So the issue is I downloaded and installed a test version of Open Live Writer 6.287; for testing curiosity.
I installed and created a test post and then tried to publish/draft to Blogger and I got an error. 

I have multiple Gmail/Blogger accounts. In Google Chrome, I was not logged into my LEHSYS account; I was actively logged into another account (Account B).

![image](https://cloud.githubusercontent.com/assets/16296509/23912933/c2e0b706-08b7-11e7-9001-445025dc8ea0.png)

Error Text:
The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

In Google Chrome, I switched to my LEHSYS account, restarted Open Live Writer and tried to post a draft and it worked. I have tried to recreate the problem, but it's gone; it's not doing it now.

At this point, I reckon this is an one-off experience.

**Comment by ScottIsAFool** [comment]
I think the usual workaround for this error is to reauthenticate with google. Usually removing the blog and adding it again should suffice.

**Comment by Laronski** [comment]
Thank you, sir. If that being the case, perhaps/maybe you guys could capture the error and see if the user wants to try to do that [reauthenticate]; relaunching the account wizard.

Always a pleasure...

**Comment by ScottIsAFool** [comment]
It's something I've thought about, yes. But the generic nature of the error we get means that might not always be the case.

**Comment by dhcowgirl** [comment]
This is happening to me today.  It's happens semi frequently.  HELP!

**Comment by romanctp** [comment]
Encountering the same issue on a fresh install. Has been happening for a few days and I decided to wait it out thinking it may be something to do with Google's servers but still not working today.

Is there a way to manually add my blogger account without having to go to Google's authentication?

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
