### ISSUE TITLE
Insert the Image from dropbox, OLW says "No" to publish; Remove the image, OLW says "Yes".

### ISSUE THREAD

**Issue by 91483** [OpenLiveWriter/OpenLiveWriter#597]
I inserted an image saved in dropbox into OLW, it didn't publish by saying "bad request" (I don't know whether same is going to happen for other images). Once I removed the image, OLW published the post. 

Can't OLW publish posts with images, or is there any other problem here?

**Comment by ScottIsAFool** [comment]
Is the image a linked image on Dropbox, using the from the web image option when inserting an image?

**Comment by Lynnea6** [comment]
I'm having the same issue with OLW not posting my pictures. Once I remove any pictures from the post it will post.  Any suggestions or help appreciated!

**Comment by ScottIsAFool** [comment]
@Lynnea6 can you please see if this solves your issue http://openlivewriter.org/tutorials/googlePhotoFix.html

**Comment by Lynnea6** [comment]
WOW! That worked!!! THANK YOU so very much....you made my night! 
Take care, 
Lynnea :) 

----- Original Message -----

**Comment by Aretino** [comment]
Al intentar postear con imagenes, no sube el post y da este error:

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

alguna sugerencia?

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
