### ISSUE TITLE
Can't execute Open Live Writer

### ISSUE THREAD

**Issue by stevenseb** [OpenLiveWriter/OpenLiveWriter#602]
Having a problem where Open Live Writer won't execute. I tried uninstalling and re-installing the program but still won't work. Log info:

2017-04-04 10:32:14> Program: Starting Squirrel Updater: --processStart OpenLiveWriter.exe
2017-04-04 10:32:15> Program: Want to launch 'C:\Users\pcuser\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe'
2017-04-04 10:32:15> Program: File C:\Users\pcuser\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe doesn't exist in current release
2017-04-04 10:32:15> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2017-04-04 10:32:28> Program: Starting Squirrel Updater: 
2017-04-04 11:52:16> Program: Starting Squirrel Updater: --processStart OpenLiveWriter.exe
2017-04-04 11:52:16> Program: Want to launch 'C:\Users\pcuser\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe'
2017-04-04 11:52:16> Program: File C:\Users\pcuser\AppData\Local\OpenLiveWriter\app-0.6.0.0\OpenLiveWriter.exe doesn't exist in current release
2017-04-04 11:52:16> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
