### ISSUE TITLE
cant publish post for blogger

### ISSUE THREAD

**Issue by syntasium** [OpenLiveWriter/OpenLiveWriter#617]
![olw](https://cloud.githubusercontent.com/assets/6773074/26283407/22978d30-3e52-11e7-9fca-226f30401033.JPG)

i dont know why this happen. i cant publish anything to blogge wit open live writer

**Comment by jongalloway** [comment]
This should be fixed in the latest release. Please verify this is still an issue in version 0.6.2.

**Comment by syntasium** [comment]
![olww](https://cloud.githubusercontent.com/assets/6773074/26522784/7f76840e-4332-11e7-96d2-fb56b063e558.JPG)

and now after i'm install new version the app cant opened

**Comment by ScottIsAFool** [comment]
@syntasium cab you please do the following:
1. Install .NET Framework 4.6.2: https://www.microsoft.com/en-us/download/details.aspx?id=53345
2. Reboot
3. Try again

**Comment by syntasium** [comment]
![error](https://cloud.githubusercontent.com/assets/6773074/26523848/25b46d1e-434b-11e7-9e44-049e26d04feb.JPG)

have instaleled net framework 4.6.2 and can open the app
but the main problem still same

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:5745
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()


i'm using win 8.1
thx

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
