### ISSUE TITLE
Update is not working for XP users

### ISSUE THREAD

**Issue by farsideoffifty** [OpenLiveWriter/OpenLiveWriter#620]
I have Windows 7 XP.  I have tried to download the new update.  I do not get anything from my desktop icon.  In order to publish anything I have to go to the download page, download it and then I can publish my blog.  Once I close out of that program I cannot use it again and have to go to the download page again

**Comment by jongalloway** [comment]
Windows XP has not been supported for Open Live Writer since release - see the FAQ's here: https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/faq.md

**Comment by farsideoffifty** [comment]
I have been using the  Open Live Writer since it came out with no problem until the update today What is up with that.  Can't you leave the older version in place for us people who use Windows XP?

**Comment by jongalloway** [comment]
Earlier you said you have Windows 7 XP. If you have Windows 7, that's a bug and we can try to fix it. We'll need your log file, info on how to get that here: https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-sending-your-Writer-log-file

If you have Windows XP, it was never intended to be supported. We're continuing to add new features, enhance Windows 10 support, etc. which won't allow us to support old code. Also, because of the way the program auto-updates, we can't really have a download for previous releases. If you're looking for Windows XP support, I'd recommend grabbing Windows Live Writer (https://www.microsoft.com/en-us/download/details.aspx?id=8621) and keeping a copy of it in case it's removed.

**Comment by farsideoffifty** [comment]
That download doesn't work either

**Comment by ruthross** [comment]
If OLW didn't work on Windows XP, then I must have Windows 7; I know I don't have 10.

Nevertheless, I cannot open the new update of Open Live Writer 6.0. The previous version was working until Tuesday afternoon. Now, when I click on the icon, the little "wheel" turns for a few seconds and then goes off. Nothing happens.

I have tried downloading the new version from www.openlivewriter.org as the FB page instructed me to do. But nothing happens. I get an Installation Failed notice and when I check something called the Set-up Log, I get this:

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

Without Open Live Writer, I am totally unable to post on my blog. It is powered by Blogger (a bitch to use) and I am running Windows 7. I had a problem with posting photos back in January, but it got fixed by your suggestion.

Can you please help me or pass this on to someone who can?

Thank you,

Ruth Ross
www.njartsmaven.com

**Comment by jongalloway** [comment]
For it to be crashing that early in the startup, it's likely due to having an older version of the .NET Framework. 

Can you try installing the latest .NET Framework update here: https://www.microsoft.com/en-us/download/details.aspx?id=53345

**Comment by farsideoffifty** [comment]
OLW worked just fine until yesterday on my Windows 7XP  It was after the update yesterday that it all fell apart 
Are you working to fix the problem ?  Thank you

**Comment by ruthross** [comment]
OK. Now what?

Ruth

**Comment by jongalloway** [comment]
So you've run the latest .NET installer and are still seeing the same problem?

**Comment by ruthross** [comment]
I installed version of .NET 4.6.2 as you suggested. 

 

When I downloaded OLW and attempted to open it, I got the following message: "Installation has failed. There was an error while installing the application. Check the setup log for more information and contact the author." 

 

When I check the setup log, I get this: 

 

"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.<Install>d__4.MoveNext()<---"

 

I am totally unable to post to my blog unless I use Blogger which is a bitch to format and requires a lot more time than OLW. 

 

I am at a total loss, and bleeding readers of my daily blog.

 

Please help me.

 

Thank you,

 

Ruth Ross

**Comment by jongalloway** [comment]
I've updated the title to reflect that this issue is about Windows 7. Open Live Writer never supported Windows XP, and there's no such thing as Windows 7 XP.

We're working on getting this sorted out. Sorry for the frustration.

**Comment by jongalloway** [comment]
@farsideoffifty Can run this to make sure you're on an up to date version of .NET Framework? https://www.microsoft.com/en-us/download/details.aspx?id=53344

**Comment by ruthross** [comment]
Thank you, Jon.

**Comment by ruthross** [comment]
Dear Jon,

 

On FB, I read a post that after installing .NET 4.6.2, the person rebooted the computer and OLW worked. I just did that and EUREKA! OLW opened!

 

Thanks for working on this.

 

Best,

 

Ruth Ross

**Comment by farsideoffifty** [comment]
I have updated the Net 4.6.2 
At the link for the new download of OLW my computer says it is malware and a threat and will not allow me to download it.  What do I do now?

**Comment by jongalloway** [comment]
@farsideoffifty See this tutorial: http://openlivewriter.org/tutorials/unrecognizedApp.html

The short story is that the old code signing certificate for Open Live Writer expired. We've signed it with a new certificate, but due to the way antivirus works, they treat new certificates as untrusted for a while until they gain some reputation.

**Comment by farsideoffifty** [comment]
I downloaded a repair for Net 10 and shut down twice before it finally seemed to make a difference at which point my old OLW began to work again.  Thank you

**Comment by ruthross** [comment]
Jon,

I am having some trouble with my tags. When I used to type in the first letter, I was automatically taken to that part of my long list. Now I have to scroll down to find what I want, or I have to type in the entire name for it to show up. What happened?

 

Otherwise, all seems well. 

 

Best,

 

Ruth Ross

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
