### ISSUE TITLE
Windows 10 Crash: Keywords file being used by another process

### ISSUE THREAD

**Issue by jongalloway** [OpenLiveWriter/OpenLiveWriter#621]
I'm seeing this error in the crash analytics for both versions 6.0.0 and 6.2.0. We should both gracefully handle the error. 

Bigger picture, I think we need to take a look at `OpenLiveWriter.CoreServices.Settings.XmlFileSettingsPersister`. This class has a  `FileStream` field that's opened and read into `Hashtables` in the `Open` method, but the file is only closed on `Dispose`. There's no need to keep it open, as all the setters and unsetters update the `Hashtables` before calling `Persist`. 

Instead, [XmlFileSettingsPersister.Open()](https://github.com/OpenLiveWriter/OpenLiveWriter/blob/a22012ccb3a9a16bc44cc591a6e612bb42418b2a/src/managed/OpenLiveWriter.CoreServices/Settings/XmlSettingsPersister.cs#L196) should access the `FileStream` with a using block so it's always closed after reading, and the `Persist` method should open / write / close.

Example stack trace:

```
System.IO.IOException: The process cannot access the file 'C:\Users\<USERNAME>\AppData\Roaming\OpenLiveWriter\Keywords\keywords_<GUID>.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at OpenLiveWriter.CoreServices.Settings.XmlFileSettingsPersister.Open(String filename)
   at OpenLiveWriter.BlogClient.BlogSettings.get_KeywordPersister()
   at OpenLiveWriter.BlogClient.BlogSettings.get_Keywords()
   at OpenLiveWriter.PostEditor.PostPropertyEditing.SharedPropertiesController.LoadTagValues()
   at OpenLiveWriter.PostEditor.PostPropertyEditing.SharedPropertiesController.OnBlogChanged(Blog newBlog)
   at OpenLiveWriter.PostEditor.PostPropertyEditing.PostPropertiesBandControl.OnBlogChanged(Blog newBlog)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.OnBlogChanged(Blog newBlog)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OnBlogChanged()
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.EditPost(IBlogPostEditingContext editingContext, Boolean forceDirty)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace()
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e)
```

**Comment by ashish191212** [comment]
Open Live Writer was working fine yesterday and today when I tried to open it, it is crashing again and again. It was showing some message earlier and now when I click top open it, nothing happens.
I checked the task manager for this and when I am trying to open the live writer it starts a process and within next milliseconds closes it.
please check the issue and fix it as I can't do any work without it,
thanks

**Comment by ScottIsAFool** [comment]
@ashish191212 Can you please raise a new issue for this. Are you able to provide any details? What version of windows are you running? Have you tried uninstalling and reinstalling?

**Comment by ashish191212** [comment]
I think the issue is with this bug that is reported from the update and if you want I can open a new case.

Here are the details:
I am using windows 7 professional 64 bit
I have tried uninstalling/reinstalling the Live Writer.
Before reinstalling, I was getting some message like "send the report to microsoft" and now I am not getting any kind of message. When I open it, a process "openlivewriter.exe *32" starts and closes automatically.

I can send you logs if you want, but you need to tell me where to find those on my system.

**Comment by dougrathbone** [comment]
Fix submitted in #1051 — replaces long-lived FileStream with open-read-close/open-write-close pattern so the settings file isn't locked between operations. Includes 8 unit tests.
