### ISSUE TITLE
Google Api Exception Error

### ISSUE THREAD

**Issue by banders03** [OpenLiveWriter/OpenLiveWriter#649]
Have been having no problems with OLW, published posts last week, Using Blogger and Windows 10. Today I'm trying to schedule a post and I get this error when I hit the Publish button:

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

Would appreciate any help,

Thanks,
Barbara

**Comment by ScottIsAFool** [comment]
Can you please remove your Blogger account from Live Writer, then just add it back in. This should clear that error.

**Comment by banders03** [comment]
I'm not allowed to remove it--I can Add, Edit, View, Remove button is not active.

**Comment by ScottIsAFool** [comment]
Ok, just add it again, then remove the original one.

**Comment by banders03** [comment]
OK, thanks.

**Comment by banders03** [comment]
OK, I was able to publish and now both accounts with the same name are active so I don't know which one to delete ;-)

Thank you!
