### ISSUE TITLE
OpenLiveWriter give error

### ISSUE THREAD

**Issue by teamgmw** [OpenLiveWriter/OpenLiveWriter#654]
Monday, July 17, 2017 10:09:15 PM

Version: 0.6.2.0

OS Version: Microsoft Windows NT 6.2.9200.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\XXXXXXXXXX\AppData\Local\OpenLiveWriter\app-0.6.2\OpenLiveWriter.exe" 

Memory Load: 77%
Total Physical: 8085 MB
Available Physical: 1786 MB
Total Page File: 16277 MB
Available Page File: 8484 MB
Total Virtual: 2047 MB
Available Virtual: 1725 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.

System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at MsSpellCheckLib.ISpellCheckerFactory.CreateSpellChecker(String languageTag)
   at PlatformSpellCheck.SpellChecker..ctor(String languageTag)
   at OpenLiveWriter.SpellChecker.WinSpellingChecker.StartChecking()
   at OpenLiveWriter.SpellChecker.SpellingManager.InitializeSession(IBlogPostSpellCheckingContext spellingContext)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditorControl.InitializeSpellChecking()
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditorControl.InitializeDocumentEditingOptions()
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl._mshtmlEditor_DocumentComplete(Object sender, EventArgs e)
   at OpenLiveWriter.Mshtml.MshtmlEditor.OnDocumentComplete()
   at OpenLiveWriter.Mshtml.MshtmlEditor.ReadyStateChangedHandler(Object sender, EventArgs ea)

**Comment by CMPAssociates** [comment]
The remote server returned an error: (403) Forbidden. This happens in Windows 10 and also in Windows 7. Allowed two posts into blogger and then began to give this error since Sunday July 23.

**Comment by teamgmw** [comment]
I have more than 100+ post on wordpress. I use windows 8.1 Pro.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
