### ISSUE TITLE
Open Live Writer Open Local Draft Error on Blogger - Backend Error [500]

### ISSUE THREAD

**Issue by justmalt** [OpenLiveWriter/OpenLiveWriter#701]
As of late last week when using Open Live Writer and I try to open an older post (Blogger) I get the error below.  The error occurs when I try to open larger quantities of posts (3000,all) however it does occur sometimes when I just try to open 50 posts.  The error occurs on multiple blogger sites I maintain and I have tried updating my blogger account in Open Live Writer or adding it as a new account.

Here is the error I receive:
The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Backend Error [500]
Errors [
	Message[Backend Error] Location[ - ] Reason[backendError] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ListRecentPosts(String blogId, Int32 maxPosts, Nullable`1 now, StatusEnum status, PostList previousPage)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by justmalt** [comment]
We update older posts all the time.  Is this not occurring for anyone else?

**Comment by justmalt** [comment]
And just like that, it started working again.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
