### ISSUE TITLE
Unhandled ArgumentException when pasting malformed smart content (OpenLiveWriter.PostEditor.ContentSources.ContentSourceManager.ParseContainingElementId)

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter#703]
### Stacktrace (first of multiple) ###

<pre>OpenLiveWriter.PostEditor.ContentSources.ContentSourceManager;ParseContainingElementId;;
OpenLiveWriter.PostEditor.PostHtmlEditing.Sidebar.ContentSourceSidebarControl;UpdateView;;
OpenLiveWriter.PostEditor.PostHtmlEditing.Sidebar.HtmlEditorSidebarHost;UpdateSidebarState;;
OpenLiveWriter.PostEditor.PostHtmlEditing.Sidebar.HtmlEditorSidebarHost;_editorContext_SelectionChanged;;
OpenLiveWriter.HtmlEditor.HtmlEditorControl;OnSelectionChanged;;
OpenLiveWriter.HtmlEditor.HtmlEditorControl.OpenLiveWriter.HtmlEditor.IHtmlEditorComponentContext;EndSelectionChange;;
OpenLiveWriter.PostEditor.PostHtmlEditing.ContentSelection;SelectElementCore;;
OpenLiveWriter.PostEditor.PostHtmlEditing.SmartContentSelection;SelectElement;;
OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditorControl;OnInsertHtml;;
OpenLiveWriter.HtmlEditor.HtmlEditorControl;InsertHtml;;
OpenLiveWriter.HtmlEditor.HtmlEditorControl;InsertHtml;;
OpenLiveWriter.PostEditor.PostHtmlEditing.ImageInsertionManager;InsertImagesCore;;
OpenLiveWriter.PostEditor.ContentEditor;commandInsertPicture_Execute;;
OpenLiveWriter.ApplicationFramework.Command;RaiseEvent;;
OpenLiveWriter.ApplicationFramework.Command;OnExecute;;</pre>

### Reason ###

System.ArgumentException: Invalid containing element id.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/249213/crash_reasons/170567318](https://rink.hockeyapp.net/manage/apps/249213/crash_reasons/170567318)

**Comment by nvella** [comment]
Doing some investigation, this exception seems to be raised on pasting Smart Content, if containingElementId passed to ContentSourceManager.ParseElementId is null, empty, or not formatted in either `scid:sourceId:contentBlockId` or `sourceId:contentBlockId formats`.

Reproduce by pasting `<iframe width="560" height="315" class="wlWriterSmartContent" id="aaa"></iframe>` into a new document, and then clicking on the element.

My stack trace:

```
System.ArgumentException: Invalid containing element id: aaa
   at OpenLiveWriter.PostEditor.ContentSources.ContentSourceManager.ParseContainingElementId(String containingElementId, String& sourceId, String& contentBlockId) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\ContentSources\ContentSourceManager.cs:line 760
   at OpenLiveWriter.PostEditor.ContentEditor.UpdateContextAvailability() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\ContentEditor\ContentEditor.cs:line 480
   at OpenLiveWriter.PostEditor.ContentEditor.ContentEditor_SelectionChanged(Object sender, EventArgs e) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\ContentEditor\ContentEditor.cs:line 1837
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.ContentEditor_SelectionChanged(Object sender, EventArgs e) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\BlogPostHtmlEditor.cs:line 493
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OnSelectionChanged(EventArgs e, IHtmlEditorSelection newSelection, Boolean moveSelectionToFont) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.HtmlEditor\HtmlEditorControl.cs:line 1542
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.FireSelectionChanged() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.HtmlEditor\HtmlEditorControl.cs:line 5159
   at OpenLiveWriter.HtmlEditor.HtmlEditorControl.OpenLiveWriter.HtmlEditor.IHtmlEditorComponentContext.EndSelectionChange() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.HtmlEditor\HtmlEditorControl.cs:line 4893
   at OpenLiveWriter.PostEditor.PostHtmlEditing.ContentSelection.SelectElementCore(IHtmlEditorComponentContext editorComponentContext, IHTMLElement e, ContentSelection smartContentSelection) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\SmartContentSelection.cs:line 260
   at OpenLiveWriter.PostEditor.PostHtmlEditing.SmartContentSelection.SelectElement(IHtmlEditorComponentContext editorComponentContext, IHTMLElement e, SmartContentState contentState) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\SmartContentSelection.cs:line 62
   at OpenLiveWriter.PostEditor.PostHtmlEditing.SmartContentSelection.SelectIfSmartContentElement(IHtmlEditorComponentContext editorComponentContext, IHTMLElement e, SmartContentState contentState) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\SmartContentSelection.cs:line 55
   at OpenLiveWriter.PostEditor.PostHtmlEditing.DisabledSmartContentElementBehavior.Select() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\DisabledSmartContentElementBehavior.cs:line 103
   at OpenLiveWriter.PostEditor.PostHtmlEditing.DisabledSmartContentElementBehavior.HandlePreHandleEvent(Int32 inEvtDispId, IHTMLEventObj pIEventObj) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\DisabledSmartContentElementBehavior.cs:line 126
   at OpenLiveWriter.Mshtml.MshtmlEditor.OpenLiveWriter.Mshtml.IHTMLEditDesignerRaw.PreHandleEvent(Int32 inEvtDispId, IHTMLEventObj pIEventObj) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.Mshtml\MshtmlEditor.cs:line 1025

```

**Comment by nvella** [comment]
Seeing as this error arises from malformed user input, we could probably do with just presenting a cleaner error, and undoing the insert.

**Comment by dougrathbone** [comment]
Fix submitted in #1041 — catches ArgumentException at the call site so malformed smart content doesn't crash the sidebar.
