### ISSUE TITLE
Google Blogger login - Unhandled exception has occurred

### ISSUE THREAD

**Issue by anwarulmaarif** [OpenLiveWriter/OpenLiveWriter#708]
Please help
login error for Google Blogger

![gambar](https://user-images.githubusercontent.com/35623318/35184808-f2a0770e-fe2c-11e7-88a0-57544db02732.png)

here the detail

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions 74.125.24.84:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OpenLiveWriter
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.exe
----------------------------------------
OpenLiveWriter.Interop
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.Interop.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenLiveWriter.CoreServices
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.CoreServices.DLL
----------------------------------------
OpenLiveWriter.Localization
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.Localization.DLL
----------------------------------------
OpenLiveWriter.Controls
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.Controls.DLL
----------------------------------------
OpenLiveWriter.PostEditor
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.PostEditor.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenLiveWriter.HtmlParser
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.HtmlParser.DLL
----------------------------------------
OpenLiveWriter.Api
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.Api.DLL
----------------------------------------
OpenLiveWriter.InternalWriterPlugin
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.InternalWriterPlugin.DLL
----------------------------------------
OpenLiveWriter.ApplicationFramework
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.ApplicationFramework.DLL
----------------------------------------
OpenLiveWriter.BlogClient
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.BlogClient.DLL
----------------------------------------
OpenLiveWriter.Extensibility
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/OpenLiveWriter.Extensibility.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.21.0.0
    Win32 Version: 1.21.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.21.0.0
    Win32 Version: 1.21.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Google.Apis.Core.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Google.Apis.Blogger.v3
    Assembly Version: 1.21.0.111
    Win32 Version: 1.21.0.111
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Google.Apis.Blogger.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.21.0.0
    Win32 Version: 1.21.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Google.Apis.DLL
----------------------------------------
Google.Apis.Auth.PlatformServices
    Assembly Version: 1.21.0.0
    Win32 Version: 1.21.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Google.Apis.Auth.PlatformServices.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Google.Apis.PlatformServices
    Assembly Version: 1.21.0.0
    Win32 Version: 1.21.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Google.Apis.PlatformServices.DLL
----------------------------------------
Squirrel
    Assembly Version: 1.4.3.0
    Win32 Version: 1.4.3.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/Splat.DLL
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/Pipit/AppData/Local/OpenLiveWriter/app-0.6.2/NuGet.Squirrel.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by nvella** [comment]
Hi @anwarulmaarif. Can you confirm if this issue is still present for you on the current version?

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.

**Comment by anwarulmaarif** [comment]
Unfortunately, I switched to Linux a few years ago, so I don't know if this issue still exists or not.
