### ISSUE TITLE
Win7:  Setup.exe Fails

### ISSUE THREAD

**Issue by Virtual-Nihilist-Blog** [OpenLiveWriter/OpenLiveWriter#83]
[SquirrelSetup1.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/59010/SquirrelSetup1.txt)
![image](https://cloud.githubusercontent.com/assets/16249774/11735313/d5c9e3f4-9f8d-11e5-852c-408d7b84ed06.png)

Downloaded OpenLiveWriter Setup.exe, but when trying to install, it reported an error immediately.  Log file and screenshot of errmsg attached.  Any ideas?  Thanks in advance...

**Comment by RobDolinMS** [comment]
Thanks for reporting @Virtual-Nihilist-Blog.  Can you share (or share a pointer to) the Setup Log?  (FWIW, I was able to successfully install on Win7.

**Comment by Virtual-Nihilist-Blog** [comment]
Hi, Rob -
I had attached a copy of the setup log to the issue when it was originally
entered (I'm looking at it now and I see a link to it right above the
screenshot of the error message).  Anyway, I've attached it to a copy of
this e-mail.  Thanks for taking the time to look into this.

On Fri, Dec 11, 2015 at 12:24 PM, Rob Dolin (MSFT) <notifications@github.com
> wrote:

> Thanks for reporting @Virtual-Nihilist-Blog
> <https://github.com/Virtual-Nihilist-Blog>. Can you share (or share a
> pointer to) the Setup Log? (FWIW, I was able to successfully install on
> Win7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/83#issuecomment-163996450>
> .
>



-- 

The Virtual Nihilist

[image: The Virtual Nihilist Blog] The Virtual Nihilist Blog
<http://virtual-nihilist.blogspot.com/>  The Virtual Nihilist On Twitter
<https://twitter.com/virtualnihilist>  The Virtual Nihilist On Facebook
<https://www.facebook.com/VirtualNihilist>

﻿2015-12-10 21:49:11> Program: Starting Squirrel Updater: --install .
2015-12-10 21:49:11> Program: Starting install, writing to C:\Users\George\AppData\Local\SquirrelTemp
2015-12-10 21:49:11> Program: About to install to: C:\Users\George\AppData\Local\OpenLiveWriter
2015-12-10 21:49:11> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\George\AppData\Local\OpenLiveWriter\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2015-12-10 21:49:11> CheckForUpdateImpl: Reading RELEASES file from C:\Users\George\AppData\Local\SquirrelTemp
2015-12-10 21:49:12> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-12-10 21:49:12> ApplyReleasesImpl: Writing files to app directory: C:\Users\George\AppData\Local\OpenLiveWriter\app-0.5.0.0
2015-12-10 21:49:12> IEnableLogger: Failed to install package to app dir: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'html' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__5(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_2.<installPackageToAppDir>b__4(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'html' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__5(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---

2015-12-10 21:49:12> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'html' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__5(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_2.<installPackageToAppDir>b__4(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'html' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__5(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_2.<installPackageToAppDir>b__4(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'html' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__5(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---
<---

**Comment by paulcbetts** [comment]
Curious. Are you sure you didn't try to run Setup.exe while the app was running?

**Comment by Virtual-Nihilist-Blog** [comment]
Do you mean did I double click on the installer and while it was running, did I double-click on it again?  If so, the answer to that is no.  If I misunderstood you, please clarify your question.

**Comment by paulcbetts** [comment]
@Virtual-Nihilist-Blog That's what I meant, yeah

**Comment by Virtual-Nihilist-Blog** [comment]
OK, thanks for clarifying, @paulcbetts

**Comment by Virtual-Nihilist-Blog** [comment]
Update:  Tried this again tonight and mysteriously, I'm no longer seeing the error reported last night.  As a result, I believe we can Close this issue.  However, I'm now getting the (incorrect) error message that it won't recognize my credentials when trying to setup my Blogger site (screenshot below).  I believe this is a known issue, so I'll look to see if there's an open issue for it and follow that discussion.  Thanks to everyone for your assistance trying to troubleshoot the original problem.

![image](https://cloud.githubusercontent.com/assets/16249774/11759560/ad0a64b2-a04a-11e5-9319-57072b4d12de.png)

**Comment by RobDolin** [comment]
Thanks for updating V-N-B.  There is a known issue with Blogger blogs that hopefully will be fixed very soon.  See Open Live Writer issue #5.
________________________________

**Comment by Obiwan2208** [comment]
Same error, different origin: System.UnauthorizedAccessException

I don't know how to upload files here, I'm a newbie in this site.
My log file is here: https://mega.nz/#!6JBn2YCJ!z0NU8lAcwKvWlBWkSHIpXgfgL9PgN38nthXDakjEZHI
