### ISSUE TITLE
OutofMemoryException --- For Big Posts 

### ISSUE THREAD

**Issue by ptrailblazer89** [OpenLiveWriter/OpenLiveWriter#843]
For Very Large Single Threaded Posts--This Exception is being thrown:

`System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()`

**Comment by nvella** [comment]
Judging by the details and stack trace you've posted, the bug seems to lie in Google's C# API implementation. Would I be able to ask what you mean by 'single threaded'?

**Comment by ptrailblazer89** [comment]
Single Threaded = Single Post...

**Comment by dougrathbone** [comment]
Fix submitted in #1065 — catches OOM in all four Blogger API Execute() calls and shows user-friendly guidance. Includes 3 unit tests.
