### ISSUE TITLE
Use MSIX for packaging and distribution

### ISSUE THREAD

**Issue by nvella** [OpenLiveWriter/OpenLiveWriter#851]
Open Live Writer is currently packaged and distributed through two different channels - a standalone Squirrel installer/updater which is uploaded to the website and other locations, and a Windows Store release. This creates a dichotomy of environments of in which Open Live Writer runs on our user's machines; Squirrel installs as a 'traditional' Windows application, where as the Windows Store version is sandboxed on a filesystem and registry level. Not only are these two different packaging/update systems to support, they're also two different runtime environments we have to support.

Switching to [MSIX](https://docs.microsoft.com/en-us/windows/msix/), the eventual replacement for MSI, will allow us to consolidate our distribution and update process for both Store and traditional releases, whilst also ensuring a consistent runtime environment across all platforms. It would also resolve many issues currently present with Open Live Writer and Squirrel, such as #20, #119, and others.

MSIX is still a relatively new technology, and whilst support on Windows 10 is built-in and quite stable, Windows 7 and 8 support is provided by [MSIX Core](https://docs.microsoft.com/en-us/windows/msix/msix-sdk/msixcore)

**Comment by gep13** [comment]
@nvella this sounds like a good idea to me.  From a selfish point of view, I would still like to see a Chocolatey Package created for installing the msixbundle.  This is currently done for example with the Windows Terminal package:

https://chocolatey.org/packages/microsoft-windows-terminal

Which embeds the msixbundle as part of the package.  For MSIX Core, we will likely get this included as a package for Chocolatey, which would allow us to take a dependency on it, when required, which would help with the installation.

**Comment by nvella** [comment]
@gep13 Definitely planning on looking to the Terminal as an example on how to model our packaging.

**Comment by nvella** [comment]
Merged my work so far into the [msix](https://github.com/OpenLiveWriter/OpenLiveWriter/tree/msix) branch. Copied the packaging project from NuGet PackageExplorer as a base; the package builds without errors however several key auxiliary files from the OpenLiveWriter.CoreServices project  (template/default.htm, etc) are missing. Not sure why they aren't being included, but would most likely be to do with the MSBuild configuration in either the packaging project or the CoreServices csproj. See log file from runtime crash below;

```
Friday, 30 August 2019 16:55:30

Version: 0.6.3.0

OS Version: Microsoft Windows NT 10.0.18362.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.Package\bin\x86\Debug\AppX\OpenLiveWriter\OpenLiveWriter.exe" 

Memory Load: 74%
Total Physical: 8094 MB
Available Physical: 2063 MB
Total Page File: 11550 MB
Available Page File: 3648 MB
Total Virtual: 2047 MB
Available Virtual: 1598 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.Package\bin\x86\Debug\AppX\OpenLiveWriter\template\default.htm'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplate.GetDefaultTemplateHtml(Boolean forceRTL, Boolean containsTitle) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.BlogClient\Detection\BlogEditingTemplate.cs:line 74
   at OpenLiveWriter.PostEditor.PostHtmlEditing.PostHtmlEditingSettings.GetEditorTemplateHtml(BlogEditingTemplateType templateType, Boolean forceRTL) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\PostHtmlEditingSettings.cs:line 150
   at OpenLiveWriter.PostEditor.PostHtmlEditing.EditingTemplateLoader.LoadBlogTemplate(String blogId, BlogEditingTemplateType templateType, Boolean forceRTL) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\EditingTemplateLoader.cs:line 36
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.GetStyledHtml() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\BlogPostHtmlEditor.cs:line 612
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.Initialize(IBlogPostEditingContext editingContext, IBlogClientOptions clientOptions) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostHtmlEditing\BlogPostHtmlEditor.cs:line 154
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OnBlogPostChanged() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\BlogPostEditingManager.cs:line 1509
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.EditPost(IBlogPostEditingContext editingContext, Boolean forceDirty) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\BlogPostEditingManager.cs:line 510
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorMainControl.cs:line 132
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorMainControl.cs:line 107
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorForm.cs:line 264
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.ApplicationFramework\SatelliteApplicationForm.cs:line 133
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace() in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorForm.cs:line 130
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e) in C:\proj\OpenLiveWriter\src\managed\OpenLiveWriter.ApplicationFramework\SatelliteApplicationForm.cs:line 76
```

**Comment by nvella** [comment]
All build errors are now mostly resolved - they were due to the project's pre-existing non-trivial MSBuild configuration which confused the MSIX packager on which files to include and which to not. I've fixed most of these, however the map templates for the (broken) Bing maps insertion are currently not being included for some reason. Shouldn't matter for now, as long as we follow standards for including auxiliary files going forward we shouldn't run into too much trouble.

**Comment by nvella** [comment]
Pushed some changes then - I am now able to create and install an appxbundle. Plugin support is disabled within MSIX for now; not sure what the best way to go about supporting this would be... Icons will also need some further work, with the small app title looking odd and the WPOST file type icon being invisible.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
