### ISSUE TITLE
Request for comments; OLW "next"

### ISSUE THREAD

**Issue by nvella** [OpenLiveWriter/OpenLiveWriter#912]
Hi all,

I first must apologise for my absence. My day job has required the majority of my focus for the last few months, leaving me very much drained when it comes to directing my attention to other large software projects. Live Writer falls into this basket for me; it's large, legacy WinForms codebase containing many workarounds from two decades ago has made it hard for myself to build up the level of drive I had when I first approached the project. In ways, I'd say I'm burnt out.

I'd like to commence on a large-scale re-factoring project to modernise Live Writer, minimise NIH, and pave the way for the implementation of long requested features such as dark mode, multi-platform, and the likes. As part of my job, I've spent a lot of time in WPF implementing a relatively complex MVVM application, and it's given me a new perspective on the technology. As such, I believe it would be a viable course of action to rebuild most of the front-facing portions of Live Writer in WPF. Here are a few of my thoughts;

- The current Open Live Writer solution is relatively decoupled, consisting of over twenty different projects. Whilst some of these, mainly `OpenLiveWriter.BlogClient` and `OpenLiveWriter.Localization`, I can see being reused, most are either directly related to the WinForms UI, implement inter-op with core Windows components such as MSHTML, or undertake problems which are largely already solved elsewhere in the .NET ecosystem, such as HTML parsing. I'm thinking it'll be a good idea if we can drop as much redundancy as possible, and refocus on the application's core responsibilities.
- We currently interface with unmanaged code for the Ribbon. Whilst the code does work, and it should for the foreseeable future, it is not very customisable (no dark mode), and the Windows interface it uses is relatively hard to find documentation for.
- If we play our cards right by implementing a UI decoupling pattern such as MVVM, and strip our reliance on MSHTML, we'll easily be able to go cross-platform. Current options include Xamarin.Forms which targets macOS and GTK (Linux), as well as Avalonia UI. I'm also keeping an eye on the in-preview .NET MAUI, announced at Build this year.
- As I touched on in the previous dot-point, it'll be very much beneficial if we can drop our reliance on MSHTML for our editing component. It'll be preferable if we can use a ready-made rich text editing component, rather than using a content-editable web view (as we currently do) and dealing with all the problems that brings. We may lose some editing flexibility, however modern blogging trends seem to lean towards relatively simple sets of formatting. The built-in WPF RichTextBox may very well be the  most suitable tool for the job here.
- Continuing on the formatting discussion, blogging has changed very much since Live Writer was first architected. Tools like static site generators have steered the ship away from large, monolithic HTML posts, and towards cleaner analogues like Markdown. I think it'd be a good idea if we kept a relatively agnostic view towards post formats; much alike a modern email client does. It would be very helpful if a blog support could specify what formats it supports (plain text, Markdown, HTML), and we provide the ability to switch between the supported formats for each post.
  - Going for a rich text component which gives us easy access to the layout tree should make it easy to translate between our internal representation and the desired output format.
- Many UI patterns are solved for us in WPF. [Fluent Ribbon](https://github.com/fluentribbon/Fluent.Ribbon) sees relatively active development and provides a high-quality Office-like Ribbon interface, including a dark mode.
- And, of course, WPF means we say bye-bye to DPI scaling problems forever 😁

These would be big changes, but in saying that I really feel it'd breathe new life into the project. It would be good if we could get a discussion going around this to work out pros/cons, additional considerations, etc.

Cheers, Nick

**Comment by rkingett** [comment]
Does this new editor allow for good accessibility implementation and keyboard interaction?

I almost use strictly markdown these days, so this is great news to hear! I mean, on multiple counts.

 This direction is good, IMO. What about screen reader accessibility, though?

**Comment by nvella** [comment]
> Does this new editor allow for good accessibility implementation and keyboard interaction?

Accessibility and keyboard navigability would be a priority, and hopefully it shouldn't be too much of a challenge if we mostly stick to off-the-shelf controls. The major concern would be in the Ribbon control; for example whilst I know Fluent.Ribbon has good keyboard support, I'm not sure how it scores accessibility-wise.

> I almost use strictly markdown these days, so this is great news to hear! I mean, on multiple counts.

Although I started blogging with Live Writer, I've also switched to editing Markdown, due to the sluggishness of Live Writer compared to most text editors. A lot of the latency is in OLW's current editor implementation; a MSHTML (read Internet Explorer) based rich text editor. I'm hoping by moving to a standard WPF RichTextBox we can keep most core functionality whilst shedding bloat and technical debt.

**Comment by rkingett** [comment]
How would writing markdown in this editor work if it's a rich text editor?

Could the default editor preference be set in settings or something? IE markdown or rich text?

There was a Microsoft editor that is really keyboard friendly, but I can't find it now. Would that work or is it too out of date? I wish I could remember the editors name now.

**Comment by nvella** [comment]
> How would writing markdown in this editor work if it's a rich text editor?

I'm thinking the approach would be quite similar to what we have now; 'Edit' and 'Source' tabs along the bottom of the window. Switching from Edit to Source would convert the internal representation (eg; a FlowDocument for the WPF RichTextBox) to the post source, with the reverse also being true.

> Could the default editor preference be set in settings or something? IE markdown or rich text?

I see no reason why not 😃 

> There was a Microsoft editor that is really keyboard friendly, but I can't find it now. Would that work or is it too out of date? I wish I could remember the editors name now.

You could be thinking of WordPad? If we decide on using the WPF RichTextBox, I'd assume it would be the same, or quite a similar editing component.

**Comment by rkingett** [comment]
Actually, no. I was thinking about [the Monico editor,](https://microsoft.github.io/monaco-editor/) or would that not work for something like this?

**Comment by Matheuslaville** [comment]
Can anyone teach how to do the step by step to install? I already downloaded the ZIP version and it got corrupted and I can't use or run it as an administrator, I don't understand this technical English, so it's hard to know how, I went to the site, I already downloaded the NUPKG and tried, but it didn't work, someone can to help?

**Comment by rkingett** [comment]
I had another look at [the Monico editor,](https://microsoft.github.io/monaco-editor/) but I can't tell how up to date it is. Ideally, I'd want an editor that others can update if you have to abandon the project.

**Comment by nvella** [comment]
> Actually, no. I was thinking about [the Monico editor,](https://microsoft.github.io/monaco-editor/) or would that not work for something like this?

Apologies for the misunderstanding - I thought you were referring to the rich text editor component, not the source editor component. The choice for the source editor is another choice we'll have to make; Monaco is definitely actively maintained and it will be for some time - it's part of VS Code. There would be complications in implementation however, it's essentially a web app and Live Writer is native Windows. [There is a third-party control to integrate it into WPF/UWP apps](https://github.com/hawkerm/monaco-editor-uwp), but I feel like it doesn't have all too much support as it stands so we might be better off doing an integration ourselves.

Another choice would be [AvalonEdit](http://avalonedit.net/) - it was originally developed for the SharpDevelop IDE. It's recently been updated to .NET Core and also sees active development.

**Comment by KUmbra-13** [comment]
Hi
It's good to know that the project will be continued. However, I must ask if before all this changes, there could be a fix for the problem of using OpenLiveWriter with Blogger, as we (users) cannot sign in normally because it has been disabled for this app.

Please forgive me if this not the right place to ask it, but it has been a huge problem since some months apparently and I'm writing this since you want to hear our thoughts.

**Comment by nvella** [comment]
Hi @KUmbra-13. I'm working on chasing this up. It's my current understanding that Google has invalidated our application for whatever reason; whether it be due to a technical change or otherwise. I joined the project long after we set up our integration with Google, so there's a bit of lost knowledge in regards to who set up the Google integration and has access to the Google developer panel. We have received patches which 'fix' the issue; in that developers have replaced the disabled Open Live Writer Google key with their own personal key. Whilst this may be fine for individual users, we very much don't want to include in the application someone's personal API key, rather than the project's or the .NET Foundation's. I wish to apologise again in regards to the delay on this matter.

**Comment by JoniWebb** [comment]
My OLW is working like a charm.  Am I the only one AND I go through Blogger to pubish.  The only problem is if I publish then make it draft and try to republish, then I have to cut and paste the blog story onto Blogger to publish.

So, I've been using LW for 14 years or so.  I would HATE to lose.  I'm all for fixing it for Blogger.  Willing to pay to use it!!!!!!
It's the best there is.  But am I the only one able to publish on Blogger?

**Comment by Catpol58** [comment]
I use OLW to post to Blogger without any problems,  Using version 0.6.30 and it publishes fine to Blogger.

**Comment by rkingett** [comment]
Is there a branch tat was created? Or is this work gonna be done in the main branch?

Is a beta ready? I'd also still love to write screen reader documentation when the time comes. For this.

**Comment by CMPAssociates** [comment]
> Hi all,
> 
> I first must apologise for my absence. My day job has required the majority of my focus for the last few months, leaving me very much drained when it comes to directing my attention to other large software projects. Live Writer falls into this basket for me; it's large, legacy WinForms codebase containing many workarounds from two decades ago has made it hard for myself to build up the level of drive I had when I first approached the project. In ways, I'd say I'm burnt out.
> 
> I'd like to commence on a large-scale re-factoring project to modernise Live Writer, minimise NIH, and pave the way for the implementation of long requested features such as dark mode, multi-platform, and the likes. As part of my job, I've spent a lot of time in WPF implementing a relatively complex MVVM application, and it's given me a new perspective on the technology. As such, I believe it would be a viable course of action to rebuild most of the front-facing portions of Live Writer in WPF. Here are a few of my thoughts;
> 
> * The current Open Live Writer solution is relatively decoupled, consisting of over twenty different projects. Whilst some of these, mainly `OpenLiveWriter.BlogClient` and `OpenLiveWriter.Localization`, I can see being reused, most are either directly related to the WinForms UI, implement inter-op with core Windows components such as MSHTML, or undertake problems which are largely already solved elsewhere in the .NET ecosystem, such as HTML parsing. I'm thinking it'll be a good idea if we can drop as much redundancy as possible, and refocus on the application's core responsibilities.
>   
>   * Simplifying the project also means we lower the bar for new contributors. The current codebase is intimidating, to say the least. It would be cool if we could open it up to anyone with general XAML/MVVM experience.
> * We currently interface with unmanaged code for the Ribbon. Whilst the code does work, and it should for the foreseeable future, it is not very customisable (no dark mode), and the Windows interface it uses is relatively hard to find documentation for. We should use an already existing OSS library like [Fluent Ribbon](https://github.com/fluentribbon/Fluent.Ribbon). It sees relatively active development and provides a high-quality Office-like Ribbon interface, as well as including a dark mode.
> * If we play our cards right by implementing a UI decoupling pattern such as MVVM, and strip our reliance on MSHTML, we'll easily be able to go cross-platform. Current options include Xamarin.Forms which targets macOS and GTK (Linux), as well as Avalonia UI. I'm also keeping an eye on the in-preview .NET MAUI, announced at Build this year.
> * As I touched on in the previous dot-point, it'll be very much beneficial if we can drop our reliance on MSHTML for our editing component. It'll be preferable if we can use a ready-made rich text editing component, rather than using a content-editable web view (as we currently do) and dealing with all the problems that brings. We may lose some editing flexibility, however modern blogging trends seem to lean towards relatively simple sets of formatting. The built-in WPF RichTextBox may very well be the  most suitable tool for the job here.
> * Continuing on the formatting discussion, blogging has changed very much since Live Writer was first architected. Tools like static site generators have steered the ship away from large, monolithic HTML posts, and towards cleaner analogues like Markdown. I think it'd be a good idea if we kept a relatively agnostic view towards post formats; much alike a modern email client does. It would be very helpful if a blog support could specify what formats it supports (plain text, Markdown, HTML), and we provide the ability to switch between the supported formats for each post.
>   
>   * Going for a rich text component which gives us easy access to the layout tree should make it easy to translate between our internal representation and the desired output format.
> * And, of course, WPF means we say bye-bye to DPI scaling problems forever 😁
> 
> These would be big changes, but in saying that I really feel it'd breathe new life into the project. It would be good if we could get a discussion going around this to work out pros/cons, additional considerations, etc.
> 
> Cheers, Nick

A Window Argument Exception blocks uploading to blogger. It also prevents you from saving the draft. The text is as follows:

System.ArgumentException: FileStream will not open Win32 devices such as disk partitions and tape drives. Avoid use of "\." in the path.
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at OpenLiveWriter.CoreServices.TempFileManager.CreateNewFile(String dir, String pattern, Boolean asDir)
at OpenLiveWriter.CoreServices.PathHelper.GetNonConflictingPath(String path)
at OpenLiveWriter.PostEditor.PostEditorFile.GetUniqueFileName(String targetFilePath)
at OpenLiveWriter.PostEditor.PostEditorFile.ManagePostFilePath(Boolean isPage, String postTitle)
at OpenLiveWriter.PostEditor.PostEditorFile.SaveBlogPost(IBlogPostEditingContext editingContext)
at OpenLiveWriter.PostEditor.BlogPostEditingManager.SaveToDrafts()

There has been a change in Blogger in July 2020:
In July, the new Blogger interface will become the default for all users. The legacy interface will still be optionally available. We recommend trying the new interface by clicking “Try the New Blogger” in the left-hand navigation. Please file any critical issues encountered. Read more. https://blogger.googleblog.com/2020/05/a-better-blogger-experience-on-web.html

**Comment by rkingett** [comment]
With quite a bit of people moving to static site generators, is there any way we could allow for connecting to these kinds of servers?

Also, this absolutely has to have Ghost support.

I'm thinking we can worry about static site generators later? But I see Ghost becoming more popular, so I do think we need to take that into account.

**Comment by rkingett** [comment]
Can't remember if this was brought up, but in OLW Next there absolutely has to be Ghost support. And, I think we should start focusing on open protocols like Ghost, WriteFreely, also, Write.as, and Plume, and other Activity Pub blogging tools. I think those platforms will become extremely important in a few years. Plus, open is easier to work with, I'd imagine?

**Comment by benyaminl** [comment]
> 0.6.30

where is the 0.6.30? why I can't found it?

**Comment by rkingett** [comment]
I don't think it's been released yet. Not even a beta! But I am waiting on the release myself.

**Comment by mdtauk** [comment]
WinUI 3.0 will be out soon, so that will help move parts of the app over to Modern XAML UI, whilst remaining and retaining as much Win32 code as you can.

WebView2 will enable you to use a modern Edge browser renderer, so should work better with more modern blog sites.

You can also consider a plugin system, so the community could build support for APIs like Wordpress or Drupal etc and eventually support more modern platforms.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
