### ISSUE TITLE
Argument Exception

### ISSUE THREAD

**Issue by CMPAssociates** [OpenLiveWriter/OpenLiveWriter#918]
A Window Argument Exception blocks uploading. The text is as follows:

System.ArgumentException: FileStream will not open Win32 devices such as disk partitions and tape drives. Avoid use of "\\.\" in the path.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at OpenLiveWriter.CoreServices.TempFileManager.CreateNewFile(String dir, String pattern, Boolean asDir)
   at OpenLiveWriter.CoreServices.PathHelper.GetNonConflictingPath(String path)
   at OpenLiveWriter.PostEditor.PostEditorFile.GetUniqueFileName(String targetFilePath)
   at OpenLiveWriter.PostEditor.PostEditorFile.ManagePostFilePath(Boolean isPage, String postTitle)
   at OpenLiveWriter.PostEditor.PostEditorFile.SaveBlogPost(IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.SaveToDrafts()

**Comment by dougrathbone** [comment]
Fix submitted in #1026 — sanitizes Windows reserved device names (CON, PRN, etc.) in GetValidFileName to prevent ArgumentException.
